- caster/bin/data/ccr/confightml.txt
Reorganized and expanded HTML CCR. Spoken forms and action objects need
to be vetted for format and usability.
Edit: Looks like formatting will screwed up by uploading to Github.
> Reorganized and expanded HTML CCR.

- caster/apps/visualstudio.py
Added several commands and fixed a couple incorrect shortcut keys
> Updates and fixes to visualstudio.py

- caster/lib/ccr/core/nav.py
- caster/lib/dfplus/state/actions2.py
- caster/lib/settings.py
Added logging to FuzzyMatchAction to facilitate data collection for #49.
> FuzzyMatchAction match logging

- caster/asynch/mouse/legion.py
- caster/lib/gdi.py
- caster/lib/navigation.py
> Fixes #116 - Multimonitor support for Legion grid

- caster/doc/readthedocs/Mouse.MD
> Adding additional documentation on the mouse modes

- caster/apps/atom.py
- caster/lib/settings.py
I made this improvement based on our discussion in #137. I'm defaulting to 30 since that should work for a wide variety of users. Advanced users can always lower this if they have a faster computer. Does that seem like a good approach?
> Adding a setting for how long to wait for Atom palette to load

- caster/apps/gitbash.py
On Windows machines gitbash runs inside the command prompt with the executable cmd. I'm updating the application context so that it works on Windows. I also added a few extra commands.
> Adding support for gitbash on Windows and added more commands

- caster/apps/atom.py
Change log
Markdown Preview Submenu Updated and Added
Sippets Submenu - Updated
Timecop Submenu - Updated
Merge Conflicts Submenu - Updated
Project Manager - Updated
Atom Beautify - Updated and Added
Git Plus - Updated and Added
Last Edit - Updated and Added
Merge Conflicts Submenu - Updated
Script - Updated and Added
---To do
Add ConfirmAction to potentially dangerous commands such as Git Plus
> Updated Atom Command Phrases

- caster/apps/visualstudio.py
>  add build and test commands to Visual Studio

- caster/lib/ccr/csharp/csharp.py
wrong syntax for C sharp lambda
> fixing lambda in c sharp

- caster/lib/settings.py
Preparation for NatLink compatibility for DNS 15
> Added default path for Naturally Speaking 15

- caster/lib/ccr/__init__.py
- caster/lib/ccr/prolog/prolog.py
- caster/lib/ccr/vhdl/vhdl.py
Set of rules for vhdl and prolog
The prolog set is very basic because it is very easy to type by voice. I Plan to later expand upon these both.
> Prolog and vhdl rules

- caster/apps/atom.py
Commented out Atom duplicated commands from caster navigation core
Updated Atom Commands especially atom integrated Github commands
Cleaned formatting
Commented out all  #Git Plus commands
Feel free to make changes!
> Updated Atom Commands

- caster/apps/gitter.py
- caster/lib/settings.py
Brings voice commands to the Gitter App.
I plan to add a little more intelligence to some of the commands.
> Support for Gitter App

- .style.yapf
- caster/lib/ccr/javascript/javascript.py
- caster/lib/settings.py
This is just a boring version bump along with a minor update to the JavaScript CCR rules to restore consistency with `var`.
> Preparation for update to `master`

- caster/lib/ccr/matlab/matlab.py
- caster/lib/ccr/r/r.py
Belated PR that adds some statistical computing languages. I'm filing this PR in part to figure out if there are any standards I should be observing -- see especially the R file, which goes beyond "core" shared elements between languages.
> Add an initial draft of R, Matlab CCR grammars

- caster/lib/ccr/core/nav.py
Add the ability to say "hug brax" to enclose the target in square brackets.
> Add [] to the hug function

- caster/lib/ccr/html/html.py
- caster/lib/ccr/sql/sql.py
Change the SQL module to output in capitals, as is standard. Added a couple more functions.
> Make the SQL module output in caps.

- caster/apps/jetbrains.py
- caster/lib/ccr/__init__.py
- caster/lib/ccr/dart/dart.py
- caster/lib/ccr/java/java.py
- caster/lib/ccr/javascript/javascript.py
- caster/lib/ccr/python/python.py
Several commands for Java, Javascript, Python, Dart, Jetbrains
> Enhancements to Java, Javascript, Python, Dart CCR language files and Jetbrains.

- caster/apps/rstudio.py
- caster/lib/settings.py
Adds basic support for RStudio. The program is pretty light on keyboard shortcuts so there is only a limited amount that can be done beyond standard caster functionality. https://support.rstudio.com/hc/en-us/articles/200711853-Keyboard-Shortcuts
> Add RStudio support

- caster/doc/readthedocs/Application commands quick reference.md
Adds a quick reference guide for the application-specific commands.
> Applications quick reference

- caster/apps/totalcmd.py
- caster/lib/settings.py
Added basic Total Commander and its Synchronize directories dialog commands
> Add Total Commander rule

- caster/doc/readthedocs/CCR languages quick reference.md
- caster/lib/ccr/__init__.py
- caster/lib/ccr/latex/latex.py
LaTeX is a markup language often used in academia for producing technical documents and scientific papers in plain text.
I have included all of the obvious commands which I could think of, but I will be using this quite a lot in the coming year so I may update it with anything I've forgotten.
https://www.latex-project.org/
> Added a LaTeX ccr module

- caster/lib/dfplus/merge/selfmodrule.py
Just fix the runtime error highlighted by pylint.
> Selfmodrule nonempty extras fix

- caster/doc/readthedocs/Voice Index.MD
Details in Update Voice Index #275
> Update Voice Index Documentation

- .pylintrc
- caster/lib/settings.py
- Converted Python comments for functions to doc strings
- Added 'disable=print-statement' to .pylintrc
- Converted print statements from 2.7 to 3.x Syntax
- Removed duplicate code from def _validate_engine_path():
> Settings.py cleanup

- caster/bin/inno/dependencies/Pip Install Dependencies.bat
Removed duplicate dependency in .bat file #295
> Remove duplicate installed dependency

- caster/lib/dev/dev.py
- caster/lib/settings.py
- caster/lib/utilities.py
> Detect browser dynamically

- caster/apps/sublime.py
- caster/doc/readthedocs/Application Commands Quick Reference.md
I've been playing with sublime over the last couple of days and have added some more key bindings to the sublime.py file. It's comparable to atom, but I think I prefer it. In particular the ability to record macros on the fly is very nice for editing blocks of text.
> Sublime updates

- caster/asynch/settingswindow.py
This is a simple extension of the existing functionality in order to address #327. A proper solution would require rewriting much of the settings window code.
> Settings window modified to distinguish between string lists and integer lists.

- caster/doc/readthedocs/CCR languages Quick Reference.md
- caster/lib/ccr/__init__.py
- caster/lib/ccr/go/go.py
I've been playing with this language a bit recently. It's pretty nice, with a fairly gentle learning curve from python.
> Add a Go module

- caster/apps/rstudio.py
- caster/apps/sublime.py
- caster/doc/readthedocs/Application Commands Quick Reference.md
I missed a couple of useful commands the first time.
Also fixed #349
> Small sublime update

- caster/apps/lyx.py
- caster/lib/settings.py
App rule for LyX. This may be added to over time but it's a start. I'm planning to document all of the mathematics functionality together separately.
> Add basic LyX functionality

- caster/lib/ccr/recording/bringme.py
Works in web browsers and Windows Explorer and makes adding new bring me commands slightly easier
> Automatically focus on the address bar when adding bring me's

- post_setup.py
- setup.py
https://github.com/dictation-toolbox/caster/issues/388
> Post install Script for Setup.py

- castervoice/bin/share/bringme.toml.defaults
- castervoice/lib/ccr/recording/bringme.py
This was done in order to make Caster more accessible by voice.
[website]
dragonfly = "https://dragonfly2.readthedocs.io/en/latest/"
"dragonfly gitter" = "https://gitter.im/sphinx-dragonfly"
caster = "https://caster.readthedocs.io/en/latest/"
google = "https://www.google.com"
"caster gitter" = "https://gitter.im/synkarius/caster"
"caster discord" = "https://discord.gg/9eAAsCJr"
[folder]
libraries = "%USERPROFILE%"
"my pictures" = "%USERPROFILE%\\Pictures"
"my documents" = "%USERPROFILE%\\Documents"
"caster user" = "%USERPROFILE%\\.caster"
filters = "%USERPROFILE%\\.caster\\filters"
rules = "%USERPROFILE%\\.caster\\rules"
data = "%USERPROFILE%\\.caster\\data"
"sick you lee" = "%USERPROFILE%\\.caster\\sikuli"
[file]
"open settings" = "%USERPROFILE%\\.caster\\data\\settings.toml"
"open …
> Bringme additions to make Caster more accessible by voice.

- castervoice/apps/githubdesktop.py
- castervoice/doc/readthedocs/Application_Commands_Quick_Reference.md
- castervoice/lib/settings.py
GitHub Desktop is probably the best way for new users to get familiar with how git works.
> Add commands for GitHub desktop

- castervoice/apps/excel.py
Apparently I accidentally closed my initial pull request to add the excel module. So I am making another one since I don't know how to reopen the initial 1 – this 1 is exactly the same as the other one. Apologies for my general incompetence using git.
> add Microsoft Excel module

- castervoice/apps/chrome.py
- castervoice/doc/readthedocs/Application_Commands_Quick_Reference.md
Few minor alterations to the chrome commands, as well as documentation.
> Chrome documentation and cleanup

- castervoice/lib/ccr/html/html.py
Added rdescript to html.py to bring it up to standard with the rest of CCR languages.
> Added rdescript to html.py

- castervoice/doc/readthedocs/CCR_languages_Quick_Reference.md
- castervoice/lib/ccr/__init__.py
- castervoice/lib/ccr/markdown/markdown.py
I've started trying to use markdown instead of latex for as much as possible (documents, slides, websites etc). It's much nicer.
> Markdown CCR module

- ReadMe.md
- castervoice/doc/Installation.md
- post_setup.py
- setup.py
This pull request is to resolve https://github.com/dictation-toolbox/Caster/issues/414.
This pull request is open mainly for people to provide feedback or suggestions on implementation.
> Post install Fix

- castervoice/apps/excel.py
- castervoice/lib/alphanumeric.py
re #409 . I don't have Excel installed so if somebody could test then that would be great, it's a fairly obvious fix though so shouldn't have made any difference.
> Tidy up phonetic alphabets

- castervoice/doc/readthedocs/CCR_languages_Quick_Reference.md
- castervoice/lib/ccr/__init__.py
- castervoice/lib/ccr/dev_commands/dev_commands.py
- castervoice/lib/ccr/voice_dev_commands/voice_dev_commands.py
VoiceDevCommands is more descriptive than Development as it signifies creation of voice commands through CCR
> Renamed development to VoiceDevCommands

- castervoice/apps/gitbash.py
I think it would be good to have a few more examples of App CCR, and I think gitbash is a good use for it since you often want to follow a command with "shock", or with a formatted name.
> Make gitbash rule CCR

- castervoice/apps/outlook.py
A couple minor changes to reply commands and empty search bar command plus some new comments.
> Outlook: improve reply commands and empty search bar command

- castervoice/doc/Installation.md
> Simplified and updated install instructions

- castervoice/lib/context.py
> Clipboard content from ASCII to Unicode

- castervoice/lib/navigation.py
> Deduplicate text copy

- castervoice/lib/ccr/core/nav.py
I wasn't sure if I should make middle click CCR but I was pretty sure about the other ones
> move some commands in nav.py to CCR from non-CCR

- castervoice/lib/ccr/core/nav.py
Reverts dictation-toolbox/Caster#481
Accidentally hit the Squash merge button
> Revert "move some commands in nav.py to CCR from non-CCR"

- castervoice/lib/ccr/core/nav.py
> fix periodic terminator comment

- castervoice/apps/chrome.py
Deleted code:
https://gist.github.com/kendonB/2ae813d01c1d90c93ae8d0e818791b6a
Addresses #495
> remove CBV commands

- castervoice/doc/CasterQuickReference.tex
- castervoice/lib/ccr/core/nav.py
@lexxish and I suggested this and @LexiconCode approved. Everything still seems to work.
> Make bow optional

- castervoice/doc/readthedocs/CCR_languages_Quick_Reference.md
- castervoice/lib/ccr/voice_dev_commands/voice_dev_commands.py
add command `dev execute` that types `.execute()` at the end of the line
> add command `dev execute` to voice_dev_commands.py

- castervoice/lib/dfplus/additions.py
- castervoice/lib/settings.py
This pull request re-implements the `IntegerRefST` class to use `ShortIntegerRef` by default and adds a settings option to disable it.
@mrob95 Are you able to let me know if this is a reasonable approach to incorporate ShortIntegerRef and tidy up that part of the codebase?
> Add short integer

- Index.md
- ReadMe.md
- castervoice/doc/Contributing.md
- castervoice/doc/Installation.md
- castervoice/doc/readthedocs/NodeRule.md
- castervoice/doc/readthedocs/Voice_Index.md
- castervoice/lib/settings.py
This reverts commit 5bffc786092c9f78b9fa37e948cbf84340200cfb.
> Revert "move all links to dictation-toolbox (#557)"

- castervoice/doc/readthedocs/CCR_languages_Quick_Reference.md
- castervoice/lib/ccr/voice_dev_commands/voice_dev_commands.py
> Voice dev commands tweak

- castervoice/apps/chrome.py
- castervoice/doc/readthedocs/Application_Commands_Quick_Reference.md
Reverts dictation-toolbox/Caster#571
Causes conflicts with #530, my bad
> Revert "add CCR rule to Chrome "

- castervoice/doc/readthedocs/Text_Manipulation.md
- castervoice/lib/ccr/core/text_manipulation.py
- castervoice/lib/text_manipulation_functions.py
Also update documentation accordingly.
> add support for the 10 digits for text manipulation

- castervoice/doc/readthedocs/Examples/Rule_Construction.md
My other branch (embarrassingly) got messed up during rebase so I am adding documentation as a separate pull request. I am aiming for `Rule_Construction.md` to be a very simple walk-through of creating and adding a rule. It is missing a few sections on actually creating the rule itself and I'll hopefully get this done this week.
> Documentation for new rule loading functions

- castervoice/lib/settings.py
The ability to toggle application stock grammars through settings.toml has been removed.
Therefore the configurations in settings.py To generate the setting should be removed as well.
Related to #596
> App settings removed in settings.py

- castervoice/apps/browser/browser.py
- castervoice/apps/browser/browser_shared_commands.py
Eliminates importing of actions directly from dragonfly, and imports from lib.imports instead. This enables browser grammars to work with Caster's aenea support. Also removes other imports now made redundant.
Thank you for the active development of this project!
None.
This enables browser grammars to work with aenea.
Tested with Linux/aenea/Win10 VM.
> Import from lib.imports in browser grammars

- castervoice/lib/ccr/core/nav.py
Sorry. I accidentally deleted sauce/dunce wally when making the modifier keys pull request. this  adds them back
> add back sauce/dunce wally

- .travis.yml
- tests/testrunner.py
Test runner script path change
> Travis update test runner path and utilize dragonfly test engine

- castervoice/lib/ctrl/mgr/grammar_manager.py
- castervoice/lib/ctrl/mgr/rule_formatter.py
- castervoice/lib/merge/mergerule.py
- castervoice/lib/merge/selfmod/tree_rule/tree_rule.py
make descriptions visible for all rules
moving the description logic
https://github.com/synkarius/Caster/issues/38
better visibility  in the console
tested mapping and merge rules
> move _set_rdescript to grammar manager

- castervoice/rules/apps/chat/MSTeamsRule.py
simple navigation, general commands and communication management
Simple mapping the rule for Microsoft teams app
Just a bunch of key bindings
no Issue
becoming quite popular tool for use at work, 
tested in application
1 new mapping rule
> Added Microsoft Teams App Rule

- castervoice/asynch/mouse/grids.py
- castervoice/lib/const.py
- castervoice/lib/navigation.py
- castervoice/lib/settings.py
- castervoice/rules/apps/mouse_grids/gridsudoku.py
- castervoice/rules/core/utility_rules/mouse_alts_rules.py
- docs/readthedocs/Mouse.md
Created a new grid-based movement system inspired by Douglas grid. It fills the screen with numbered 3 x 3 squares and lets you move to and drag from positions anywhere on the screen. It is several seconds faster to render than the other 2 grids.
None
Dragon's mouse grid is abysmal. I use voice control full-time and needed something better. I tried the other grids in Caster and found them to be useful but not quite enough. I am a professional software engineer and have worked with grid-based storage in both hobby game development and university research. This experience allowed me to optimize the method used by the other 2 grids and extend it to create my own.
I used my grid for over a month successfully (with iterative improvements/fixes). I tried it with all sorts of programs, even a …
> Added Sudoku grid

- castervoice/lib/utilities.py
- castervoice/rules/core/utility_rules/mouse_alts_rules.py
This PR should fix for all MouseGrid's failing to be in the foreground or out of focus.
#171
#194
#500
Often the MouseGrid's commands would not function as expected sometimes behind the overlay. This is because the grid is out of focus and not in forefront. The long-standing issue is it's been unpredictable to calculate the time between creating the grid and when to focus. Try to focus too soon and it fails to focus because the MouseGrid overlay does not exist yet.
This issue is resolved by looping over the active windows until a match is found within a range. The functions to evaluate windows and so on are done through dragonfly it can be easily made cross-platform. Testing will need to be done on Mac and Linux in the future to check if TK behaves with focusing.
This is been tested on …
> Fix MouseGrid out of focus

- castervoice/rules/core/text_manipulation_rules/text_manipulation.py
- castervoice/rules/core/text_manipulation_rules/text_manipulation_support.py
- docs/readthedocs/Text_Manipulation.md
One of the most common corrections i have to make
is to change the capitalization of a word and recently dictated text.
This commit introduces the "capital"  text manipulation command,
which can be used to make a word or character
upper or lowercase.
I've tested this was every combination of characters versus dictation, direction, and uppercase versus lowercase versus default that i could think of
- **I couldn't find any tests for test manipulation**
> add command for capitalization

- castervoice/lib/utilities.py
In the near future when using Dragonfly CLI to launch Caster CMD/terminal window title is renamed to `Caster: Status Window`. It will send to Terminal `clear` which clears out the text. Same behavior that already exists with the `natlink messaging window`.
In the future if GUI to replaces command prompt/terminal this could be easily reworked to accommodate.
- Re-factored  window_exists/get_window_by_title without `win32ui`
None
Prep for launching Caster through Dragonfly CLI
This is been tested with the `natlink messaging window` and the future `Caster: Status Window`.
> Clear Caster status window enhancements

- castervoice/rules/ccr/rust_rules/rust.py
- castervoice/rules/ccr/rust_rules/rust2.py
- docs/readthedocs/CCR_languages_Quick_Reference.md
I find these useful, and I think that they would not
cause any controversy, so I thought I would share.
I've been coding rust with caster for several months now. i'm a bit tired of replacing my branch, so I thought I would share my changes.
I will comment in line with my rationale for each one.
Note: I have also renamed the `bind` command to `assign` because `bind` is constantly confused with `find` from the VS code grammar. I chose not to make that change in this commit because renames are controversy.
I rebooted Dragon, ensured that there were no syntax errors, and tested all of the new or changed commands in an empty editor.
> Some tweaks to the rust grammars

- castervoice/rules/apps/editor/jetbrains.py
Add executable name to support [Rider](https://www.jetbrains.com/rider/).
Opened Rider and tested for Jetbrains commands.
> Add support for JetBrains Rider

- castervoice/rules/apps/editor/vscode_rules/vscode.py
- castervoice/rules/apps/editor/vscode_rules/vscode2.py
- docs/readthedocs/Application_Commands_Quick_Reference.md
Some of these changes are debatable,
so I just wanted to put this out there as
a suggestion:
*  ~~For the `<action> line` commands, I made the word `line`
no longer optional.
**I did this because dragon was often interpreting
`deli two` as `delete two`
and unexpectedly deleted the second line
instead of two characters.**~~
*  move "show terminal" from
non-ccr to ccr.
** I did this because I very frequently want to say things like
`terminal cargo build`**
to run a command without waiting
for the terminal to be expected.
* ~~Add alternative `[manpower]` to the `command palette` command.
**On my bad microphone, `command palette` was interpreted
as `manpower`**
too often.~~
*  Add `[<text>]` to the `command palette`
command
**so you can say the command
you want in a single statement**
*  Add …
> Enhancements for VSCode Grammar

- castervoice/rules/apps/editor/vscode_rules/vscode2.py
- docs/readthedocs/Application_Commands_Quick_Reference.md
#210  Description
Add a command for holding down the Alt key, while clicking the left mouse button.
I use this to specifically for setting the cursor position in the Visual Studio the terminal.
I added the command and rebooted Dragon. Then I entered a long line in the terminal, and said `altar kick` while hovering the mouse over the middle of it. The mouse cursor moved to the indicated point as expected.
> Add command for alt-click for VS code

- .travis.yml
- castervoice/lib/const.py
- castervoice/lib/ctrl/dependencies.py
- castervoice/lib/dev/dev.py
- castervoice/lib/navigation.py
- castervoice/lib/settings.py
- castervoice/lib/utilities.py
- castervoice/lib/virtual_desktops.py
- castervoice/lib/windows_virtual_desktops.py
- castervoice/rules/ccr/recording_rules/bringme.py
- castervoice/rules/core/navigation_rules/window_mgmt_rule.py
- requirements-mac.txt
- setup.py
Changes necessary to start using Caster on macOS
These changes make Caster functional on platforms other than Windows.
To make Caster available on all major desktop systems.
Run Caster on macOS
> Initial macOS support

- castervoice/rules/apps/editor/vscode_rules/vscode2.py
I didn't see a way to move tabs across editor panes, so I added one myself.
I tested this in the VS editor
- [ X] New feature (non-breaking change which adds functionality)
- [X ] I have checked that my code does not duplicate functionality elsewhere in Caster.
- [X ] My code implements all the features I wish to merge in this pull request.
> Move tab left/right in VsCode

- castervoice/rules/apps/chat/webexteams.py
- docs/readthedocs/Caster_Commands/Application_Commands_Quick_Reference.md
- tests/rules/apps/test_rule_modules.py
Add a rule for Webex Teams
Integration with Webex Teams. I used the keyboard shortcuts documented [here](https://help.webex.com/en-us/7wr87q/Keyboard-Navigation-and-Shortcuts-for-Cisco-Webex-Teams). I didn't implement meetings/calls since it seems strange to me use commands while on a call - they could be added later. I didn't implement markdown - the markdown rule should be used instead.
A few notes:
- Wasn't sure what to call the search/find command. The UI calls it "search" but I could see a case to use "find" as well. I ended up using "search | find" like vscode
- There is some text formatting for bold/italicize/underline which uses "standard shortcuts" which could be put somewhere shared in the future. I saw some modules implement it themselves so I did the same
- Commands were kept …
> Add Webex Teams Rule

- castervoice/rules/core/navigation_rules/nav.py
> Trivial change: Expand function key range to include F10-F12

- castervoice/rules/ccr/recording_rules/bringme.py
> Trivial change: Fixed discord link and log.txt bringme path

- castervoice/rules/ccr/recording_rules/bringme.py
I took the approach in `simple_alias.py` and simply ported it over to `bringme.py`.
Bring me should not be CCR - my main problem I was having was that I was getting complexity errors due to having so many bringme items.
I made the changes, rebooted caster, and just made sure that bring me still worked as well as it now not giving complexity errors when enabled along with other languages.
P.S. I actually don't know how to run unit tests any more. We should add the command for that to the contributing document.
> Convert bringme feature to non ccr

- docs/readthedocs/User_Dir/Caster_User_Dir.md
Avoid confusion between use of term "User Directory" here and the Natlink User Directory
> Clarified Caster vs Natlink User directory docs

- castervoice/rules/apps/mouse_grids/gridlegion.py
> Remove Playback from legion mouse click

- castervoice/rules/apps/editor/unity.py
- docs/readthedocs/Caster_Commands/Application_Commands_Quick_Reference.md
I have added grammar for unity. They should be pretty self-explanatory, but I'd like other unity users to test it and give input on naming.
Several users showed interest in a Unity grammar.
Manually testing all the commands within unity.
> Add Unity3D grammar

- castervoice/rules/apps/editor/vscode_rules/vscode2.py
- docs/readthedocs/Caster_Commands/Application_Commands_Quick_Reference.md
- Fixed `join line` and `full screen`.
- made `preview` optional in `keep preview open`.
- added `format selection` as alternative to `format that`.
- added `format (doc | document)`
- updated documentation.
#794 
Manual testing and searching for potential clashes.
> vscode grammar update

- castervoice/rules/ccr/css_rules/css.py
- docs/readthedocs/Caster_Commands/CCR_languages_Quick_Reference.md
Added CSS rules
I created a new rule file called CSS rule and then wrote documentation in language quick reference file
I am a front-end web developer and I needed this. With these CSS rules now I can write CSS files even faster than typing them with hands and auto complete
I've tested every single one of commands by saying them with voice, and every one of them work as intended. I also used this rule in my day to day projects to make sure that written commands are usable in real world scenarios.
I've used Windows as OS, sublime text and Visual Studio code as text editors for testing and using and it works flawlessly
> added CSS commands

- castervoice/lib/merge/ccrmerging2/ccrmerger2.py
> BugFix: result instead of results

- Install_Caster_DNS-WSR.bat
- Install_Caster_Kaldi.bat
Seems like this could be helpful for discovering/debugging python issues. Feel free to close if not desired.
> Add active python/pip info in install scripts

- castervoice/asynch/mouse/grids.py
Quick fix adding the dimensions of the screen
Fixes #733
See #733
Using Kaldi with two monitors and saying "Sudoku 2" then, for example, "7".
> Get Sudoku to work on multiple monitors

- Run_Caster_DNS.bat
- Run_Caster_Kaldi.bat
> Fix typo Runnig -> Running

- castervoice/rules/apps/atlassian/jira.py
- docs/readthedocs/Caster_Commands/Application_Commands_Quick_Reference.md
- tests/rules/apps/test_rule_modules.py
Added support for Atlassian Jira server. Jira is an agile task management platform. It should work with Jira cloud as well.
This adds integration with Jira. I use it frequently.
I validated each command works. I also use this rule set frequently.
> Add Atlassian Jira rule

- castervoice/lib/ctrl/configure_engine.py
- castervoice/lib/ctrl/mgr/engine_manager.py
- castervoice/lib/settings.py
Ping @kendonB 
This implements Caster mic sleep timer. This allows the microphone for you go to sleep after X seconds for all speech recognition engines based on the last successful recognition. 
It's easy to forget that your microphone is "on" causing unwanted recognition when a user's attention is preoccupied.  Having a timeout for the microphone go to sleep minimizes unwanted recognition.
This is been tested with DNS/DPI
**Note** DNS/DPI has its own built-in sleep mode timer defaults to 5 minutes. Caster mic sleep timer will not work as expected beyond DNS/DPI 5 minutes default timer (microphone will go to sleep prematurely). if you increase the default timer to greater than 5 minutes anything under caster mic sleep timer will work as expected.
Todo: mock settings for unit test
> Implemented mic sleep timer

- castervoice/lib/utilities.py
This update `get_clipboard_files` to work with Linux and `default_browser_command` to work cross-platform. This lays the groundwork for Bringme to be updated for Linux.
https://github.com/dictation-toolbox/Caster/issues/680
Windows has a clipboard formats CF_HDROP which returns a list of files/folders. There is no equivalent for `CF_HDROP` in Linux. Files and folders are represented in different ways within the clipboard depending on distribution. 
Here's some work I've done for Linux.
- get_clipboard_formats uses xclip to grab the available formats contents of the clipboard.
- enum_files_from_clipboard clipboard contents that processes begins with file:// or generic lines of output. Then generates a list by processing into unverified absolute file/folder paths.
- get_clipboard_files …
> Bringme Prep Linux

- castervoice/lib/settings.py
- docs/readthedocs/User_Dir/Caster_User_Dir.md
This pull request allows the user to configure their user directory via the environment variable `CASTER_USER_DIR`. 
Issue #842.
See #842
On Ubuntu, I ran `CASTER_USER_DIR=~/.local/share/caster-dev /usr/bin/python3 -m dragonfly load _*.py --engine kaldi  --no-recobs-messages`
and manually checked that the user directory was created correctly.
> configure user directory

- castervoice/lib/navigation.py
window_exists expects windowname in the first place. So that the second part always returned false.
> Fix Grids could be called multiple times

- castervoice/rules/core/keyboard_rules/keyboard.py
Reverts dictation-toolbox/Caster#869
The import for button_dictionary_1 is not properly initialized and updated.
> Revert "add missing keyboard keys"

- castervoice/rules/core/keyboard_rules/keyboard.py
This PR changes out the `cat_spec_and_reverse_3` function to more obviously be correct.
#868 
Bug
Just once on the text engine - please retest @LexiconCode @jdcai
> fix cws bug

- castervoice/rules/core/keyboard_rules/keyboard.py
Reference https://github.com/dictation-toolbox/Caster/pull/869
> Add missing keyboard keys

- castervoice/lib/ctrl/configure_engine.py
- castervoice/lib/settings.py
- docs/readthedocs/Caster_Settings/settings.md
add the ability to turn off the Casters sleep mic timer 
- does not affect DNS/DPI's sleep built-in timer
- increased mic_sleep_timer to default 5 minutes to match DN/DPI default
- does not affect DNS/DPI's sleep built-in timer
increased mic_sleep_timer to default 5 minutes to match DN/DPI default
> add mic_sleep_timer_toggle

- setup.py
Reverts dictation-toolbox/Caster#884
> Revert "change setuptools email"

- docs/readthedocs/Rule_Construction/Advanced_Caster_Rules/ContextStack.md
I think `A few points about the ContextSet:` implies that the topic is changing, so hopefully my edit will override that potential assumption.
I was confused reading the documentation and I think this could prevent confusion in the future
- [x ] I have read the CONTRIBUTING document.
- [x ] I have updated the documentation accordingly.
> ContextSet Doc Clarification

- castervoice/lib/navigation.py
- castervoice/lib/utilities.py
- castervoice/rules/apps/mouse_grids/griddouglas.py
- castervoice/rules/apps/mouse_grids/gridlegion.py
- castervoice/rules/apps/mouse_grids/gridrainbow.py
- castervoice/rules/apps/mouse_grids/gridsudoku.py
- castervoice/rules/core/utility_rules/mouse_alts_rules.py
Implement function context for mouse grids
- Function contexts monitors if grid process is available for all grid systems.
- Removed `focus_mousegrid` as the grid system no longer relies on foreground focus but on the active process.
- Removed `kill_grids_and_wait`
- Added `weight=2`  to cancel commands
Summoning MouseGrid's checking for the following:
Checked if grid overlay activates
Checked if appropriate grid rule active
Checked if more than one grid rule active when grid is active
Checked if grid cancel and re-summon correctly
Needs to be tested on Linux
- Checked if grid cancel and re-summon correctly
That should validate the mechanism for polling and closing the process.
> Implement function context for mouse grids

- castervoice/asynch/mouse/grids.py
- castervoice/lib/settings.py
- castervoice/rules/apps/mouse_grids/griddouglas.py
- castervoice/rules/apps/mouse_grids/gridrainbow.py
- castervoice/rules/apps/mouse_grids/gridsudoku.py
- docs/readthedocs/Installation/Windows/Dragon_NaturallySpeaking.md
- requirements-dev.txt
- requirements-mac-linux.txt
- Made dragging in Sudoku work like it does in the other two grids.
- Did what's required to get the grids to work in Ubuntu
- Use `pyscreenshot as ImageGrab`
- Remove `self.hide()` in Rainbow. This was causing the grid to draw on the wrong monitor in a two monitor setup. **This is what I'm most uncertain about. I don't know what function it served previously. We'll need to test on multiple systems.**
- Moved to monitoring the process to detect if the grid Context is there **for all systems**. This is probably better than the existing way of just looking at the window title.
- Changed the number-action mapping so that they're consistent. A simple change but it should get another set of eyes to make sure I didn't mess up.
None.
Mouse grids don't work on Linux.
Verbally trying out the …
> Enhanced grids linux + complete Sudoku

- castervoice/lib/context.py
This PR leverages new functionality dragonfly to synchronize the clipboard. Additional improvements
- Handle cross-platform clipboard key specs to invoke clipboard 
- Add key override for non-standard key specs to invoke clipboard
- Add timeout parameter monitoring for clipboard change
> Simplified Copy/Paste without altering clipboard

- castervoice/lib/ctrl/mgr/exclusivity_manager.py
- castervoice/rules/core/engine_manager_rules/dictation_sync_rules.py
Implement DictationSinkRule for exclusivity_manager
Refer to https://github.com/dictation-toolbox/Caster/issues/914
Makes the caster on a caster sleep modes more accurate with the dictation sink. See description
> Implement DictationSinkRule for Exclusivity Manager

- castervoice/lib/settings.py
> Update transformers path in settings

- .github/dependabot.yml
- .github/workflows/dependabot-merge.yml
- castervoice/lib/ctrl/mgr/loading/load/reload_fn_provider.py
Add Dependabot Auto-Merge
Apply security fixes as identified by Dependabot which pass GitHub Actions CI.
See https://docs.github.com/ja/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions
Works on my other repositories; tested by developers of Dependabot and Dependabot Auto Merge.
> GitHub dependabot
