dictation-toolbox/Caster

- caster/bin/data/ccr/confignavigation.txt
- caster/lib/navigation.py
This PR adds an explicit "set format" command. As discussed in the comments on #86, this allows you to separate the selection of a format from the command used to output formatted text, reducing the number of things you need to say for a single utterance.
Usage example: "set format laws spine bow" followed by "format some identifier".
> Add "set format" command.

- caster/bin/data/ccr/configjavascript.txt
A few of the javascript commands were a missing space between () and {} in the output. Neither Visual Studio or Sublime text correct this automatically, which means that some code blocks end up with inconsistent formatting, which I then have to correct manually.
> Javascript CCR: more consistent code block formatting.

- caster/bin/data/ccr/configjavascript.txt
JavaScript makes heavy use of anonymous functions passed as parameters to other functions as callbacks and event handlers. The current "function" command in the JavaScript CCR contains a NAME and a semicolon at the end, both of which then need to be deleted. This PR adds an "anon funk" command, which produces the following output, suitable for embedding in a parameter list:
```
function () {
|<-- cursor here
}
```
> Javascript CCR: Add "anon funk" command

- _caster.py
- caster/asynch/mouse/grids.py
- caster/asynch/mouse/legion.py
- caster/lib/navigation.py
This PR adds support for multiple monitors when using any of the caster mouse grid commands. Usage is simple: simply append the (optional) monitor number to the grid command you want to use. If you don't specify a monitor number, the grid will display on the primary monitor (monitor 1).
For example, saying "rainbow 2" will display the rainbow grid on monitor 2. To display the rainbow grid on the primary monitor, you can say either "rainbow 1" or simply "rainbow".
> Multi-monitor support for grid commands

- caster/lib/ccr/core/punctuation.py
More often than not, DNS hears "type seven" when I say "pipe sim". "Pipe symbol" is more phonetically distinct, and easy enough to remember and say, so I thought it might be good to give users that option out of the box. Feel free to reject the PR if you think this falls into the category of things I should address via filter functions.
> Allow "pipe (sim | symbol)" for a more phonetically distinct option

- caster/lib/settings.py
Fixes a bug introduced by 98eba8f9fd3cd5
> Fix "cannot concatenate 'str' and 'int' objects" error in settings.py

- caster/lib/pita/selector.py
To potentially help with #49.
I ported a similarity calculation function I created to compare youtube video titles to theTVDB episode titles. For that purpose, it returned the correct episode better than 9 out of 10 times, but I don't know how well it will work for matching abbreviations. For example, if I try to match "test function", the symbol "test" has a higher score (39) than "tstfnc" (37) because of the token sequence boosting I added.
One thought I had was to change the sequence boosting to work with non-contiguous sequences. In this case, the entire sequence of "tstfnc" would count as a sequence, even though most of the letters aren't contiguous, because those letters appear in the same sequence in both.
> Ported a similarity calculation algorithm

- caster/apps/explorer.py
- caster/apps/visualstudio.py
- caster/lib/ccr/core/nav.py
- caster/lib/navigation.py
- caster/lib/settings.py
* Added Windows Explorer grammar and updated Visual Studio grammar.
* Replaced the use of the Playback action in the right and left click commands with direct calls to the underlying user32 api calls to improve performance. The existing commands rely on the Dragon engine to perform mouse clicks, and this often causes a lag of a few hundred milliseconds for me. Sometimes it would also cause double-click to fail altogether.
* Added "next/prior window" command. "Next window" and "prior window" both do the same thing and are simply a shortcut for saying "switch window" followed by "shock". Convenient for repeatedly switching back and forth between two windows.
* Added mouse wheel scrolling, with the following caveat. For some windows, scrolling works regardless of whether the mouse pointer is …
> Mouse improvements, app grammar updates, next/prior window

- caster/doc/readthedocs/Mouse.MD
I worked through the [Alternate Mouse Movement Modes video](https://www.youtube.com/watch?v=UISjQBMmQ-I) and noticed that the [documentation](http://caster.readthedocs.io/en/latest/caster/doc/readthedocs/Mouse/) is missing the colors for the rainbow command, so I thought it would be nice adding them. I also changed the structure of the documentation page - please feel free to reject this pull request if you don't like it (e.g. the documentation got longer). The mouse commands were missing too, however, _curse up left 30_ did not work for me. To make it work I had to replace _curse_ by _mouse_ and use only one direction: _mouse up 30_. If this is an issue only I have, please feel free to edit this or let me know.
> Update mouse documentation

- caster/doc/readthedocs/Mouse.MD
When writing the mouse documentation for the last pull request (#147) I used the online tool http://dillinger.io/. Now I noticed that Github uses a differen syntax and therefore does not display the documentation correctly. It should work now.
> Fix mouse documentation (GitHub Flavored Markdown)

- caster/lib/ccr/core/nav.py
- caster/lib/textformat.py
- Remove implicit "set format" (see #158). The "set format" command also now prints the new text format to the NatLink window (see "peek format" command below)
- Added "clear caster formatting" command. I find that sometimes it's convenient to be able to output text without any added formatting into a program that's not supported by Dragon (eg comments in code files).
- Added "peek format" command, which will print the current text format to the NatLink window. For example, it will print something like `Text formatting: laws spine (this-is-a-test)`.
> Text formatting usability improvements

- _caster.py
Minor update to fix the occasional "no handlers could be found for logger" messages that occasionally appear in the NatLink status window. Now if an error bubbles up to one of the Dragonfly Action classes, it should print the exception and stack trace information, which we can use for debugging.
> Fix "no handlers could be found for logger" error messages

- .gitignore
- caster/apps/gitbash.py
I added the terminal I use to access git to the list of app contexts where the git rules are active. I also tracked down an issue I was just having over the weekend where the context was getting activated when I tried to connect to Wi-Fi through the system tray. The new start menu in Windows 10 is provided through `ShellExperienceHost.exe`, which was causing a false match against `sh`.
I also added the cruft that Emacs likes to leave everywhere to `.gitignore`. If you would like me to resubmit it separately, please let me know.
> context fixes

- caster/apps/chrome.py
I sorted through the keybinds for Chrome, removing unnecessary or redundant ones, regrouping related ones, and adding some that weren't there. I also cleaned up the imports.
I tested most of the keybinds. A few weren't triggering their intended functions, but that may be an issue with the newly updated browser or some extension I'm running. I left them in under the assumption that they would either start working again as things got sorted out or they would work for others where they haven't for me. At the very least, the utterances should be unique enough that they shouldn't cause any false hits.
I have more I'll be submitting as a separate file at a later date which expect certain extensions to be installed and work for specific sites like Facebook, Gmail and Google Docs.
> updates to Chrome keybinds

- caster/lib/ccr/recording/history.py
- caster/lib/settings.py
1. Say I had created a sequence of commands using the phonetic alphabet (e.g. "Press control Charlie"). The sequence failed to save  because of the slash  character associated with the phonetic pronunciation. This was because the code was attempting to remove the slashes. However, the type was an immutable tuple and could not be assigned to. I fixed it by changing it to a list.
2. Once created, the sequence did not load properly because the name was read in as Unicode characters from the JSON file. A downstream dependency was not expecting Unicode and failed. Fixed by immediately converting it to an ASCII string when read.
> History fixes

- caster/apps/eclipse.py
- caster/apps/flashdevelop.py
- caster/doc/readthedocs/examples/rules/Caster Rules.MD
- caster/lib/dfplus/hint/hintnode.py
- caster/lib/dfplus/merge/ccrmerger.py
- caster/lib/dfplus/merge/mergerule.py
- caster/lib/tests/complexity.py
- caster/lib/tests/unit/merger.py
- caster/user/filters/examples/modkeysup.py
- caster/user/filters/examples/scen4.py
The current use of get_name preferentially returns the pronunciation instead of the name of a rule.
This change updates `get_name` to be `get_pronunciation`  so the method name is more in line with the underlying logic.
Original:
```python
def get_name(self):
return self.name if self.pronunciation is None else self.pronunciation
```
Updated:
```python
def get_pronunciation(self):
return self.pronunciation if self.pronunciation is not None else self.name
```
> Change get_name to get_pronunciation to clarify what's being used.

- _caster.py
Right now, caster has a [try/except on boot](https://github.com/synkarius/caster/blob/master/_caster.py#L27-L65), but, in an error case, everything still breaks due to a fatal error after the `except` (MergeRule throws as not defined on [line 76 of the same file](https://github.com/synkarius/caster/blob/master/_caster.py#L76)). So, at the moment, the only thing this block does is make the error log more confusing. 
**Before change, an error shows up as an undefined MergeRule.**
**After, the actual error is let through.**
This PR just removes that try/except for now.
> Remove try/except around startup.

- caster/lib/settings.py
This PR:
- Removes some unused default settings values
- Refactors settings.py with
- More docstrings
- More PEP-8 formatting
- Fewer global mutations
- Separates public and private methods
- Moves to merging a default nested dict against the live settings. This allows separating out the defaults in the future.
On my machine, I can boot with a vanilla generated settings file and create one from scratch as needed.
The diff of generated settings files is here: https://www.diffchecker.com/KT7nL3P0
> Rework and clean up setting.py

- caster/lib/ccr/cpp/cpp.py
- caster/lib/ccr/csharp/csharp.py
- caster/lib/ccr/haxe/haxe.py
- caster/lib/ccr/java/java.py
- caster/lib/ccr/javascript/javascript.py
- caster/lib/ccr/python/python.py
- caster/lib/ccr/rust/rust.py
- caster/lib/dfplus/merge/mergerule.py
This pull quest removes the `auto` and `token_set` properties as discussed in #192
Ideally this should make the code base easier to approach as a beginner, because there are fewer things to get tripped up on.
> Remove unused rule data

- caster/apps/vscode.py
- caster/lib/ccr/javascript/javascript.py
I was looking through the repository of @betaorbust and I thought these commits would be a good fit for the main repository. I see no problem with merging the module for VS Code, but I thought I would seek comments from others on the changes to JavaScript CCR.
I would've just cherry picked the changes for VS Code, but I'm still feeling my way through GitHub and trying to make sure proper attribution is given. Besides, I figured it might be considered rude to merge someone else's work without explicit permission.
> VS Code and JavaScript CCR fixes

- caster/lib/ccr/core/nav.py
- caster/lib/textformat.py
I have added a partial format command which allows the user to utter any dictation but keep the first n (1 up to 4) words. The rest of the dictation is used as context to improve the accuracy of the first words. Example usage:"single format end of time"=>"end", which minimizes the chances of Dragon actually outputting "and" while at the same time not polluting the command pool with new commands.
> Partial format

- caster/lib/dfplus/merge/gfilter.py
- caster/lib/navigation.py
- caster/lib/settings.py
- caster/lib/utilities.py
This attempts to fix some long-standing issues with the way Caster interacts with the clipboard and reorganizes file I/O to be forwards compatible with Python 3. The files were reformatted through [YAPF](https://github.com/google/yapf) using the attached configuration file. I'm open to different styles and I will try to keep the style changes to a single commit in the future.
[style.txt](https://github.com/synkarius/caster/files/1823011/style.txt)
This patch changes Caster to prefer Unicode when interacting with the Windows clipboard. No attempts are made to explicitly handle legacy text localization. My hope is that Windows will do the right thing when it handles auto conversion. To support this, file I/O has been rewritten to assume and encode for UTF-8 in a way that is compatible with …
> Unicode fixes

- caster/asynch/mouse/grids.py
- caster/asynch/mouse/legion.py
- caster/bin/inno/dragonfly_upgrade.bat
- caster/doc/Installation.md
- caster/lib/settings.py
Fix for issue #172,dpi settings properly accounted for.
> Legion DPI fix

- caster/bin/inno/dependencies/pip.bat
- caster/lib/settings.py
The premise is the search for DNS across all drives and to check DNS version.
>  Detect alternate drive DNS install locations and versions #242

- caster/bin/inno/dependencies/pip.bat
- caster/lib/settings.py
Do to issues #248 with Win32_Product and wmi I have re-implemented #242 #243 methods to find DNS path via the registry.
Overview of changes
- Does not rely on Win32_Product() from Wmi
- Wmi dependence removed for _winreg
- Renamed _validate_natspeak() to _validate_engine_path() as its engine agnostic
- Renamed exe_path to engine_path for clarity
- Renamed DisplayVersion to DnsVersion for clarity as needed
- Edited comments for clarity
> Reimplementation methods to find DNS path via the registry

- caster/doc/readthedocs/examples/rules/Caster Rules.MD
Documented that both line and in-line comments are supported in rule filter files #265.
Added code blocks with Python code formatting.
> Documented python comments are supported in rule filter files #265.

- _caster.py
- caster/doc/readthedocs/Alias.MD
- caster/doc/readthedocs/CCR.MD
- caster/lib/ccr/recording/alias.py
- caster/lib/tests/unit/mergerule.py
Both in the documentation and the CodeBase 'vanilla alias' has been replaced with just 'alias' This is to reflect an earlier change that simplified alias https://github.com/synkarius/caster/pull/245
> Reworked CodeBase to reflect simplified alias command. 

- caster/lib/dev/dev.py
- caster/lib/settings.py
- caster/lib/utilities.py
Browser path was hardcoded in settings. This attempts to get default browser from the registry an falls back to `os.startfile` (with the opening in background annoyance). The utility function can be used elsewhere
> Detect browser dynamically

- caster/bin/inno/dependencies/Pip Install Dependencies.bat
- caster/bin/inno/dependencies/Pip Uninstall Dependencies.bat
- caster/bin/inno/dependencies/pip.bat
Updated to [dragonfly2 ](https://github.com/Danesprite/dragonfly) distribution 
- Removed unnecessary dependencies that are installed by the dragonfly community fork
- Removed psutil no longer relevant to Caster
- Added Uninstall Script 'Pip Uninstall Dependencies.bat'
- Renamed Pip.bat' to 'Pip Install Dependencies.bat'
- Add toml dependency.
**Reference**
Simplify Caster install #217 
Caster as a package #246
> Updated Caster dependencies .bat files

- .pylintrc
- caster/apps/eclipse.py
- caster/asynch/hmc/homunculus.py
- caster/lib/navigation.py
- caster/lib/utilities.py
Either fixes errors highlighted by pylint, or hides them as appropriate. After this pylint -E should not display errors. Unfortunately it has to be run as pylint -E, but despite an ugly warning, the exit code of pylint is 0. Something to maybe consider for #274 if tests are not ready at the moment
> Hide or fix pylint errors 

- caster/doc/readthedocs/CCR languages quick reference.md
- caster/lib/ccr/r/r.py
I've re-factored the R module. There were a large number of commands which all did basically the same thing – write a particular function and then move inside the brackets – which I've reduced to just a couple of commands, with options in the extras. There are a few benefits to this:
* Reduces code volume and repetition.
* Makes it easier and more intuitive to add new extras.
* Makes it easier to modify how the command works, e.g adding a prefix.
For consistency, I have made the prefix for all ggplot commands "graph". I have also added a prefix – "fun" – to the command which produces R functions. A small reduction in speed for a large gain in phonetic distinctness and a reduction in mistakes.
> Cleaning up the R module

- .pylintrc
- caster/apps/eclipse.py
- caster/asynch/hmc/homunculus.py
- caster/lib/navigation.py
- caster/lib/utilities.py
Either fixes errors highlighted by pylint, or hides them as appropriate. After this pylint -E should not display errors. Unfortunately it has to be run as pylint -E, but despite an ugly warning, the exit code of pylint is 0. Something to maybe consider for #274 if tests are not ready at the moment
> Hide or fix pylint errors  

- caster/lib/settings.py
Restored previous comments as needed and moved relevant doc strings inside functions with correct syntax.
> Hotfix doc strings in settings.py

- caster/lib/dfplus/merge/ccrmerger.py
Option three defined in 'Alternative approaches managing settings for 'alias'/'chain alias' and 'record from history' spec #302'
> Converts ccr.toml [selfmod] as true instead of false.

- caster/lib/ccr/core/nav.py
A couple of commands which I have added for text navigation, which I find very useful.
* Splat command adds functionality for deleting whole words, in both directions, using the c-del and c-bkspc keystrokes. eg `splat three`, `splat ross`.
* Shift click does what it says on the tin.
I may make one or two other changes this week so I will update the docs in one go, separately.
> Add "splat" and "shift click" commands

- caster/lib/ccr/core/nav.py
- caster/lib/navigation.py
Inspired by #278. A few points:
* If the user just says "spark", only ctrl-v is executed. This is important to make sure that the command still works as expected for images, files etc.
* Whether or not "bow" is needed as a closer is questionable, I've left it in for now.
* The original (ages ago) suggestion for this feature suggested that the command should actually edit the clipboard in situ. I personally think this is a better solution as it preserves the original data.
Sample command: "shackle cut spark yell bow". Capitalise the whole line.
EDIT: I tried changing this to use Text() instead of copying in and out of the clipboard. It's more elegant but unfortunately takes ages (potentially minutes) to execute long strings, so I think the clipboard is the better option.
> Add complete spark formatting functionality

- caster/lib/alphanumeric.py
- caster/lib/ccr/core/alphabet.py
- caster/lib/ccr/core/nav.py
- caster/lib/ccr/latex/latex.py
When grammars are combined for CCR the `extras` get overwritten by the latest one as they are merged.  This behavior introduced a bug in the last merge which caused the spoken alphabet to wrap the letter in `SHIFT` keystrokes.
In this case, the `Choice` extra "big" existed several times for the same purpose but was implemented slightly differently. I made these uses consistent and simplified things.
I also refactored part of the code for the spoken alphabet to handle capital letters in a more platform neutral way.
I left `letters` in `alphanumeric.py` as it was because I couldn't find any use of it in the code base. I think the function might be an artifact from when @synkarius was originally developing Caster.
> Fixed bug introduced in #326

- caster/apps/fman.py
- caster/doc/readthedocs/Application Commands Quick Reference.md
- caster/lib/settings.py
fman is a lightweight, two-pane file manager which can pretty much entirely be controlled using keyboard commands.
Note 1: Actions which use standard keypresses (return to open a file, tab to change pane, space to select files, etc) don't have their own commands.
Note 2: This imports Text and Key from .lib.actions in readiness for #316 .
> Add fman support

- caster/apps/__init__.py
- caster/apps/atom.py
- caster/lib/ccr/__init__.py
- caster/lib/settings.py
After losing several hours to 'misfeatures' last night, I decided to spend some time refactoring this module. 
* Simplified and updated available commands.
I added two helper functions to make adding various types of commands more streamlined. Some broken commands were fixed and some of the trigger phrases were rewritten to fix ambiguities (`"git (custom|run)"` in place of `"git custom|run"`, for example).
* Removed commands which duplicated Caster Core functionality.
There were several commands which use nonstandard utterances to duplicate functionality provided in the core of Caster. Additionally, the `"paste"` command in particular would trap me for several minutes at a time due to the potential for very high repeat counts.
* Miscellaneous minor bug fixes.
This includes fixing the …
> Update Atom Command Rules

- caster/lib/ccr/r/r.py
"Operators & and | perform element-wise operation producing result having length of the longer operand.
But && and || examines only the first element of the operands resulting into a single length logical vector."
The double logical operators are seldom preferred in R and tend to result in error prone code.
> Change lgl operators to element wise in r.py

- caster/apps/file_dialogue.py
- caster/doc/readthedocs/Application Commands Quick Reference.md
- caster/lib/settings.py
Implements #348 
Creates an app rule which identifies file dialogues by title and provides commands for navigating them. This method works in the programs I have tested it with.
To do:
* ~~test on more programs~~ Seems to work in all standard save/open dialogues. Some programs have their own, but I'm not sure there is much that can be done about that beyond creating separate rules for each. 
* ~~add more potential file dialogue window names to the context - browse? open folder? open project?~~ title finding seems to be fairly fuzzy, so "open" works for "open file" etc
* ~~Think about whether grammar can be improved~~
* ~~docs~~
This is an excellent idea though. Wish I'd thought of it!
> File dialogue rule

- caster/bin/inno/dependencies/Pip Install Dependencies.bat
- caster/bin/inno/dependencies/Pip Uninstall Dependencies.bat
- caster/doc/Installation.md
A couple of modifications to the installation process/instructions:
* Changed the order so that all dependencies are installed at the same time using the .bat file.
* Added instructions for modifying natlink settings using the GUI.
* Added "future" to the dependency install, this seems to be part of NatLink's move to python 3.
I'm open to suggestions for anything else which isn't clear or any more potential issues.
> Update installation instructions

- caster/asynch/hmc/h_launch.py
- caster/asynch/hmc/hmc_ask_directory.py
- caster/asynch/hmc/hmc_confirm.py
- caster/asynch/hmc/hmc_recording.py
- caster/asynch/hmc/homunculus.py
- caster/asynch/mouse/grids.py
- caster/asynch/mouse/legion.py
- caster/asynch/settingswindow.py
- caster/lib/settings.py
- caster/lib/utilities.py
Fixes a bug whereby UI windows don't launch if any of the folders in the directory tree begin with "caster".
> UI path finding bug fix

- caster/lib/navigation.py
- caster/lib/textformat.py
1. Fixed a bug whereby formats would not be normalised before being executed, so for example "gerrish bow" would produce "some Text" rather than "someText".
2. Fixed a bug resulting from the above bug fix, whereby pasting from the Caster clipboard without specifying a format would automatically produce lowercase text. Clarified the logic of the paste command.
> Text formatting bug fixes

- caster/lib/textformat.py
This was my solution to the issue addressed by @mrob95 in #368. I've been sitting on this for a while, as can be seen from the date in the branch name.
The tactic I took solving this was to simply apply the existing normalization to dictated text. There are several more extensive changes I would like to make in this area, but I thought this was an acceptable minimum for fixing the bug. I explicitly wanted to avoid messing with paste functionality due to that being part of the larger scope of changes I would like to make in the future.
The meaningful changes are:
* Line 1 makes `str` Unicode. This is important to be able to handle the (currently optional) changes to the Windows implementation of `Text` in Dragonfly. This section also has some basic cleanup of the imports.
* Line 34 is a …
> Text normalization bug fix

- _caster.py
- caster/lib/ccr/recording/alias.py
- caster/lib/dfplus/merge/selfmodrule.py
Re #358 
* Removed CCR from regular alias
* Both regular aliases and chain aliases can now be added both with a voice command and through the GUI. "alias example command" will set the spec as "example command". "alias" will bring up the GUI.
Seems like an intuitive way of doing things but I'm happy to take suggestions.
> Alias updates

- ReadMe.md
- How to Speak Code
- Making your own Dragonfly and Caster rules
How to Speak Code should complement the example videos for people to practice.
Making your own Dragonfly and Caster rules should jumpstart people thinking how to create their own grammars. Thus providing context for the rest of the documentation.
> Updated ReadMe links to include dictation code example doc and rule creation,

- castervoice/apps/typora.py
- castervoice/lib/settings.py
Put simply [Typora](https://typora.io/) gives me a seamless keyboard driven experience. It removes the preview window, mode switcher and syntax symbols of markdown source. What you see is what you get style of editor.
> Implemented Typora application grammar

- castervoice/doc/readthedocs/Application_Commands_Quick_Reference.md
- castervoice/doc/readthedocs/CCR_languages_Quick_Reference.md
- castervoice/lib/ccr/dev_commands/dev_commands.py
I've added documentation for the new Outlook, Excel and development grammars.
I've also made some modifications to the development grammar to make it a little more intuitive, and also removed the mouse movement command, which is not really related to development and is almost identical to the "curse" command in core navigation.
> Development command modification + documentation

- castervoice/lib/ccr/core/alphabet.py
- castervoice/lib/ccr/core/nav.py
- castervoice/lib/ccr/core/numbers.py
- castervoice/lib/ccr/core/punctuation.py
Differentiates Caster commands from other commands sources such as Dragon. Thus brings caster core commands in line with the rest of the CCR standards regarding rdescript grammar identification.
> Added to "Core:" rdescript for the core Caster ccr files. 

- castervoice/doc/readthedocs/CCR.md
- castervoice/lib/dfplus/merge/ccrmerger.py
This has been bugging me for a while. 
Previously, declaring a non-CCR rule to be loaded at the same time as a CCR app rule added with `control.nexus().merger.add_app_rule` didn't work. As far as I can tell this is because the `non` property doesn't survive the `MergePair` process. Ideally it would be fixed there but I have never worked with that code so thought it better to leave it alone. This just stores the `non` before merging and restores it afterwards.
> Fix non-CCR for app rules

- post_setup.py
This opens up a new command prompt window during install providing instructions or showing any errors in the post install script.
An effective workaround for requiring the verbose argument during PIP install.
> Post install enhancements with logging in new window during pip install

- castervoice/apps/chrome.py
- castervoice/apps/rstudio.py
- castervoice/apps/sublime.py
- castervoice/doc/readthedocs/Application_Commands_Quick_Reference.md
- castervoice/lib/ccr/python/python.py
- castervoice/lib/context.py
- castervoice/lib/ctrl/nexus.py
- castervoice/lib/temporary.py
Stores the currently highlighted text in a temporary variable, to be Retrieved after some other action. If no text was highlighted, an empty string will be stored.
Sample usage:
```
"find that": Store() + Key("c-f") + Retrieve() + Key("enter")
```
In order to enable use with web URLs, Store() takes a string, space, which will replace all space characters, and a bool, remove_cr, which if true will remove any newlines in the selection, to avoid them triggering the request early.
Sample usage:
```
"wikipedia that":
Store(space="+", remove_cr=True) + Key("c-t") +
Text("https://en.wikipedia.org/w/index.php?search=") +
Retrieve() + Key("enter")
```
There are cases where you may want the same function to do different things depending on whether or not text was highlighted. The action_if_no_text …
> Create an action wrapper for read_selected_without_altering_clipboard

- castervoice/apps/sublime.py
- castervoice/doc/readthedocs/Application_Commands_Quick_Reference.md
Mostly minor updates and I still need to document these.
Couple of commands of interest which could easily be replicated in other editors:
* `go to <dict> [<filetype>]` - allows for example "go to sublime pie" which will take you straight to sublime.py. Doesn't work for tricky filenames but makes navigating a fair bit simpler.
* action lines - for example "copy line thirty three" or "select line five to fifteen".
> Couple of new sublime rules

- castervoice/lib/settings.py
Enabling print rdescripts by default is meant for onboarding new users to see the command history caster. 
dev_commands set to true so that the configdebug.txt can be utilized without without editing settings.
Both of these commands enabled will allow for documented recommended workflowsfor new users.
> By default print_rdescripts and dev_commands are set to true

- castervoice/lib/actions.py
This was discussed on the dragonfly channel. The default pause between each keystroke in a Text spec is 20ms, so for larger specs there is a noticeable lag before the execution is finished. I've dropped it to 3ms, but it could probably go lower. I've never encountered an application which had trouble with this rate of fire.
> Speed up Text execution

- _caster.py
- castervoice/lib/actions.py
Hopefully fixes #399 . I don't have a setup at the moment to test this though so needs testing to make sure it fixes the problem.
> Fixed user rule loading bug

- _caster.py
- castervoice/lib/dfplus/merge/ccrmerger.py
The basic behaviour is this:
* Saying "disable caster" disables all CCR rules. It doesn't disable non-CCR app rules but I don't think this is too important.
* Saying either "enable caster" or enabling any CCR rule re-enables CCR.
* CCR remains disabled after reboot.
Main use cases are:
* Using caster for one specific thing (coding, maths etc) but not for everything.
* Disabling caster while you're doing a specific task (eg dictating text).
> Enable and disable CCR

- _caster.py
There are two functions that check for updates and have commands for updating PIP packages for caster and dragonfly. In addition are two installed methods `PIP` and the `Classic` install.
For the classic install updating the caster the package is not desired.
To understand how this function works It relies on the folder structure of a classic install to determine the install type. The function checks if `castervoice` folder in the same folder as ` _caster.py` file. Conversely the PIP install `castervoice` is not in the same folder. A classic install won't check for caster pip package updates.
> Function to determine caster install type

- castervoice/lib/dev/dev.py
Resolves #378 Move configdebug.txt file to user space 
Tested deleting configdebug.txt in data folder and .caster 
if configdebug.txt is ever deleted in the data folder it will be replaced with the default configdebug.txt.
- processed with yapf
> Copied configdebug.txt to user space

- castervoice/lib/ccr/recording/bringme.py
Fixes bringme.toml is blank on new installations of caster #400 
Tested deleting bringme.toml and .caster includes yap formating.
if bringme.toml is ever deleted it will be replaced with the default bringme settings.
> Copied bringme.toml.defaults to user space as bringme.toml with yapf

- _caster.py
- castervoice/asynch/sikuli/sikuli.py
Fix #463 by reloading `sikuli.py` and #468 whose root cause was that the grammar for controlling Sikuli was [overriden](https://github.com/dictation-toolbox/Caster/blob/develop/castervoice/asynch/sikuli/sikuli.py#L64-L65) instead of extended. In the process of the fix I restructured `sikuli.py` a bit. What's not so elegant is that when a profile change occurs the old grammar isn't unloaded. However, at the moment I can't think of real disadvantages this could constitute in practice. I couldn't make the `refresh sick you Lee` command work, but replaced it by `terminate sick server` and `launch sick server`. It's only one more command and achieves the same thing.
Note that this doesn't fix #464. As described in this issue: Whenever you expect something to happen which isn't happening (e.g. …
> Sikuli Fix #463,#468

- castervoice/doc/CasterQuickReference.tex
There was an error in the "Template-based navigation" a section. It said "jump in" instead of "fill <target>".
> Fixed error in section "Template-based navigation"

- castervoice/apps/chrome.py
- castervoice/lib/ccr/core/nav.py
- castervoice/lib/ccr/python/python.py
- castervoice/lib/dfplus/merge/mergerule.py
- castervoice/lib/dfplus/state/actions.py
- castervoice/lib/dfplus/state/stack.py
- castervoice/lib/dfplus/state/stackitems.py
Currently, the accepted formatting for a caster command looks something like this:
```
"function": R(Text("def ():") + Key("left:2"), rdescript="Python: function"),
```
We have the verbal command, R - which creates a registered action, the actual dragonfly objects to be executed, and an rdescript written by whoever wrote the grammar to describe the command.
There are a number of problems with this construction.
1. It's long, often requiring multiple lines to define a single command.
2. It's verbose, only about half of the character count is actually useful code, the rest is verbiage.
3. It's a bug magnet, with a lot of potential for misplaced commas and brackets and misspelled words.
4. rdescripts are inconsistent between different authors and are a pain to write.
The combination of these …
> Redesign rdescripts

- _caster.py
Fixes #508 by loading userspace rules only once - when DNS is started for the first time - and not when you switch to a different profile.
> Make userspace rules work after changing profile

- castervoice25/lib26/ccr27/voice_dev_commands28/voice_dev_commands.py
I first put in the '+' because the Pause action is often used in conjunction with other actions and so often requires the plus before it. But after more experience using these commands, I think it is better just to be consistent and not put the plus in front.
(by the way, this is my first ball request made using the gui as opposed to the command line so it works)
> Remove the '+' from the `dev pause' command.

- castervoice/lib/settings.py
Addresses #516. Added error handling for case when 'PROCESSOR_ARCHITEW6432' is not set as an environment variable.
> Handle case when 'PROCESSOR_ARCHITEW6432' is not an environment var

- castervoice/lib/ccr/core/nav.py
Change some mouse commands and the undo/redo commands to CCR.
This is a redo of #483  which I am now closing (because I'm having some difficulties with git and that one had a mistake). I have not added or deleted any commands. I have just moved them to CCR.
> make some commands CCR in nav

- castervoice/lib/actions.py
- castervoice/lib/ccr/html/html.py
This will request contextually changes imports `Text `to `Paste` based on AppContext for all supported Jetbrains products.
`from dragonfly.actions.action_paste import Paste as Text`
> HTML workaround for Jetbrains IDE auto complete #541

- castervoice/apps/vscode.py
- castervoice/lib/dfplus/merge/ccrmerger.py
- castervoice/lib/dfplus/merge/mergerule.py
Small alteration to make adding app CCR rules easier. If no `mwith` is defined in the rule then this will default to `CCRMerger.CORE` when the rule is added rather than throwing an error. This is a sensible default I think and saves importing `CCRMerger` into every rule. Relevant to #571.
> Add default for mwith

- castervoice/apps/chrome.py
I increased the wait time after pressing control c, and I took out other unnecessary waits. Also, the command spec "duplicate window" was causing some crazy behavior I don't know why, possibly because that is another command somewhere? Anyways, I changed it to "duplicate tab in the window" which is working well now.
> fix duplication commands in chrome

- castervoice/lib/navigation.py
- castervoice/lib/settings.py
- castervoice/lib/utilities.py
Finally resolve #357 the least inventive way. Reasons in the issue, unable to fix toml. By the way if more exotic languages where Unicode is needed for dictation are supported, this will become an issue again with aliases, macros etc.
> Revert clipboard to use json

- _caster.py
Caster updates sometimes require a mandatory upgrade to the latest dragonfly. The purpose of this pull request is to add minimum version checking to dragonfly. Implements https://github.com/dictation-toolbox/Caster/issues/568
> Minimum version checking for dragonfly.

- castervoice/lib/control.py
As mentioned in #589  I have implemented a series of functions in `control.py` to simplify and standardise the API for adding rules.
The only question I have at the moment is about lines like:
```
if settings.SETTINGS["apps"]["firefox"]:
```
Which only load app rules if the relevant value is set to true in the settings. Is there a good reason why this is necessary? Does anybody need the ability to disable particular app rules (perhaps RDP users)? @LexiconCode
> Rule loading functions in control.py

- castervoice/lib/dfplus/merge/mergerule.py
So that instead of e.g. "VSCodeNonCcrRule: command" it will just print "VSCode: command"
> Improve rule naming in rdescripts

- castervoice/lib/ccr/recording/history.py
Fixes #526 macro "times" command to repeat macros
Credit goes to @mrob95
> Fixes the record from history "[times <n>]" command repeat macros

- castervoice/lib/ccr/recording/alias.py
- castervoice/lib/ccr/recording/bringme.py
- castervoice/lib/control.py
To recreate:
1. Add a filter rule in words.txt e.g. "tango -> trap"
2. Add an alias with the same name e.g. "Alias tango"
3. restart
Produces: 
```
File "C:\Users\Mike\Documents\GitHub\casterfork\castervoice\lib\dfplus\merge\gfilter.py", line 221, in spec_override_from_config
rule._mcontext, rule._mwith)
TypeError: __init__() takes exactly 2 arguments (11 given)
-- skip unchanged wrong grammar file: C:\Users\Mike\Documents\GitHub\casterfork\_caster.py
-- skip unchanged wrong grammar file: C:\Users\Mike\Documents\GitHub\casterfork\_caster.py
```
I assume this has pretty much been the case since forever as the chances of finding it are fairly small.
Fixed for the moment by not running filters on self modifying rules. It doesn't really make sense to filter them anyway as they are set by the …
> Fixed Selfmodrule filter bug

- _caster.py
- Switch to `os.path.dirname(os.path.abspath(__file__)` to get `current file` path not `working directory` via `getcwd`.
- Improved readability installtype by returning install type strings `classic or pip` instead of a bool.
> Fixed installtype function

- Index.md
- MANIFEST.in
- castervoice/bin/share/FilterRules/words.txt
- castervoice/doc/index.md
- castervoice/doc/readthedocs/CCR.md
- castervoice/lib/ccr/recording/bringme.py
- castervoice/lib/dfplus/merge/gfilter.py
- castervoice/lib/settings.py
Since `word.txt` represents type of Rule Filter in the documentation it should be loaded from `.caster\filters`.
**Changes and Additions**
- Loads`word.txt` in `.caster\filters` instead of `.caster\data`
- Renamed `FILTER_WORDS_DEFS_PATH` to `SIMPLIFIED_FILTER_RULES_PATH` to reflect documentation.
- Renames documentation `Rule Filters Simplified` to `Simplified Filter Rules`.
- Added words.txt to `filters/examples`
- Added `words.txt `to `MANIFEST.in` include in the PIP package
> Load word.txt from .caster\filters and documentation update

- castervoice/lib/navigation.py
Closes #634.
I have changed the mouse functions in `castervoice.lib.navigation` to use the  `Mouse` action. This makes commands such as "psychic" work with aenea mode.
The logic for 7 of the mouse functions has also been moved into a new `mouse_click()` function. This is just for readability really.
> Simplify Caster mouse functions and use the Mouse action instead

- _caster.py
- castervoice/lib/ctrl/dependencies.py
When developing Caster sometimes dependencies change between releases or require a locked version. This whole request implements a method of informing users of the change in dependencies.
- Allows maintainers to define minimum and specific version of dependencies. To be used between releases as a method of informing contributors of changes with dependency.
- Checks for missing dependency reading `requirements.txt`
- Enhanced message that guides the user to install dependencies.
- Suppresses traceback
- If a dependency is missing the main thread sleeps for 15 seconds with both WRS and Natlink
- Moves all dependency related functions out of `_caster.py` to `dependencies.py` except for the grammar.
> Classic install: Enhancements to check dependencies for required versions and missing dependencies.

- castervoice/lib/ccr/recording/bringme.py
- castervoice/lib/utilities.py
- docs/readthedocs/Bringme.md
- mkdocs.yml
Adding files and folders should work from Windows Explorer (and everywhere files can be copied). Closes #575. Path detection in the end with copying and `win32clipboard` Remarks:
- There was a bug, adding anything did not work?
- Uses Dragonfly's clipboard as well as pywin32's win32clipboard
- The link "caster discord" displays an expired Discord invitation - is there a Discord channel?
> Bring me for files and folders

- castervoice/lib/ccr/voice_dev_commands/voice_dev_commands.py
this pull request fixes a bug where the same dictionary was included in two different extras without making a deep copy. words.txt acted on that dictionary twice, when it should have just acted once.
This pull request simply makes the change to create a deep copy.
> fix voice_dev_commands

- castervoice/lib/ccr/core/punctuation.py
This pull request reverses some incorrect changes to `punctuation.py` in #590 where some repeats disappeared. @mrob95 can you think of any other places that this type of error could have occurred?
> fixed punctuation

- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
This pull request adds a template for adding pull requests.
None.
Having a template for pull requests helps to add a little discipline to the process and helps to remind contributors what needs to be done before something gets merged.
I have done no testing as it needs to be merged in order to test with GitHub.
> add pr template

- docs/CasterQuickReference.tex
- docs/readthedocs/Bringme.md
I have removed references to bring me from `CasterQuickReference.tex` and tidied up the `Bringme.md` file.
#629 
As discussed in #629, we like to pull everything we can out of the LaTeX file and move the content into ReadTheDocs. The bring me documentation in ReadTheDocs was a little untidy and I have brought it in line with the style in `Mouse.md` and `Text_Manipulation.md`.
No testing yet as I do not have `mkdocs` working on my computer yet. I will check that it is correct immediately after merging.
> Bring me docs

- castervoice/lib/temporary.py
Changed output of Retrieve() from text to dragonfly paste action
`Text(output).execute()` vs `Paste(output).execute()`
Current implementation `Text(output).execute()` for `Retrieve()` does not handle multiline text. This is not noticeable except for applications where pressing `enter` sends text. E.G chat application like Gitter. `Text` seems to use enter key between each line. This means if you Retrieve() a multiline text it sends each line as its own message.
To work around this dragonfly `Paste` achieves the same functional purpose of `text` without the drawbacks mentioned.
I've tested this with multiline and single-line text fields with varying implementations of `Store() Retrieve()` and in gitter/sublime.
> Changed output of Retrieve() from Text to dragonfly Paste action

- castervoice/apps/gitter.py
- docs/readthedocs/Application_Commands_Quick_Reference.md
Added `store and retrieve` to enhance gitter. The default behavior is the same as the original and enhancements come in when text is selected.
**Example:**
bold would print out `****` then the cursor would move left 2 times. Next dictate `example test` Final result being `**example test**`.
With the new commands highlighting `example test` and say `bold` produces the final result result `**example test**`.
**Limitations**
~~I excluded utilizing it on commands that were multiline. Store and retrieve does not handle multiline execution well~~. Waiting for https://github.com/dictation-toolbox/Caster/pull/652 as a fix.
**Possible Planned Features**
~~A feature yet to implement is if no text is selected to carry out an action of moving the cursor as needed.~~ Done …
> Added store and retrieve to gitter

- docs/readthedocs/GRAMMAR_DOCUMENTATION_TEMPLATE.md
This pull request adds a template for grammar documentation (e.g. `Mouse.md`, `Text_Manipulation.md`, and `Bringme.md`).
None.
There was a lot of style inconsistency in the documentation and this pull request aims to prevent that. It provides a template for adding new documentation, as well as defining some style conventions (subject to change upon discussion). In particular, it asks that can phrases be referred to using _italics_ and variables in the command phrase spec be referred to using `backticks`.
No testing yet.
> add grammar documentation template

- castervoice/lib/ccr/core/nav.py
I previously added a few one syllable commands for control/shift arrow keys. These are experimental, I have found that fird is commonly misrecognized for bird which is another command I added. so I'm replacing it with firch which after using for a week is working much better. similar changes may be required for other commands. Alexander's [Rosetta sheet](https://docs.google.com/spreadsheets/d/1pk2gwTFbMebgYSsrxIFsZ-QvpEPWCybF8ypdeBvfBsg/pubhtml) is a decent resource for this sort of thing. for example, it contains a one syllable alphabet apparently from voice code.IO.
> fird -> firch

- .travis.yml
- castervoice/lib/tests/mocks.py
Fixes tests. You can see now that mock alias classes are duplicate, but that is also, Apart from configuration, true about their original counterparts.
> Add refresh method to mock ChainAlias and use test discovery on Travis

- .travis.yml
- castervoice/lib/tests/testrunner.py
Playing with Travis, I think a better way is to 1.use testrunner, since it initializes the text engine, which I do not know how to do via commandline with test discovery, and 2. fail the script commands early
> Use testrunner for Travis

- castervoice/lib/ccr/markdown/markdown.py
Added `store and retrieve` to enhance MarkdownCCR. The default behavior is the same as the original and enhancements only activate with text is selected.
**Example:**
The command `insert <image>`   would print out `![]():` then the cursor would move left 3 times. Next with the word `MyPicture`  highlighted dictate  `insert <image>`. The final result being `![MyPicture]()`.  with the cursor at the end.
With the new commands highlighting any text will place the text in the appropriate context of the command.
https://github.com/dictation-toolbox/Caster/issues/650
Leverages store and retrieve to highlight text. Current features it only leverages the keyboard this allows greater mixed input from selecting text Mouse or MouseGrids.
It's been tested within the Gitter (Has trouble with the enter …
> MarkDown CCR: Added store and retrieve

- castervoice/lib/ccr/python/python.py
Added `store and retrieve` to enhance Python CCR. The default behavior is the same as the original and enhancements only activate with text is selected.
**Example:**
The command `function`  would print out `def ():` then the cursor would move left 2 times. Next with the word `awesome`  highlighted dictate  `function`. The final result being `def awesome():`.  with the cursor at the end
With the new commands highlighting any text will place the text in the appropriate context of the command.
https://github.com/dictation-toolbox/Caster/issues/650
Leverages store and retrieve to highlight text. Current features it only leverages the keyboard this allows greater mixed input from selecting text Mouse or MouseGrids.
It's been tested within the VScode with CCR and Non-CCR commands
not …
> Added Python CCR store and retrieve features

- castervoice/lib/ccr/core/nav.py
In dragonfly2, Key("&") works but Key("/") does not; you need to use the longhand Key("slash") . Similarly with The hyphen, comma, and colon. This pull request changes the button dictionaries to use that longhand format in those cases. This applies to the commands for pressing buttons (e.g. modifier keys) and the voice dev commands.
When I originally made a pull request to this effect #666, I did so improperly and so I closed that and and replacing it with this one.
> add longhand punctuation names

- castervoice/asynch/hmc/hmc_recording.py
- castervoice/lib/ccr/recording/history.py
Fixes #546
There are some words that still fail to be recognized in specs ("naïve"), but this seems to be Dragonfly issue in general
> Allow Unicode characters in history

- castervoice/lib/settings.py
Sets user directory with Permissions check with Roaming fallback
Checks permissions for the `user directory` and uses `AppData\Roaming` as a fallback on Windows for the caster user profile.
Reported issue in the gitter channel by @ethangoldstein 
Due to restrictions IT managed devices permissions may be restricted in the user directory.  
Tested by using invalid paths for user directory.
> Sets user directory with Permissions check with fallback location

- _caster.py
- castervoice/lib/ctrl/dependencies.py
This pull request sys.exec_prefix to find pip or pip.exe path. 
@Versatilus partial credit goes to utilizing sys.exec_prefix which inspired this fix.
@alexboche reported in gitter.
```
  | Exception from starting subprocess [None, 'search', 'dragonfly2']: argument of type 'NoneType' is not iterable
--|--
  | Error loading _caster from C:\Users\alex\Documents\Caster-master\_caster.py
  | Traceback (most recent call last):
  | File "C:\NatLink\NatLink\MacroSystem\core\natlinkmain.py", line 331, in loadFile
  | imp.load_module(modName,fndFile,fndName,fndDesc)
  | File "C:\Users\alex\Documents\Caster-master\_caster.py", line 72, in <module>
  | class MainRule(MergeRule):
  | File "C:\Users\alex\Documents\Caster-master\_caster.py", line 90, in MainRule
  | R(DependencyUpdate([pip_path, …
```
> Find pip cross platform without environment variable

- castervoice/lib/context.py
Windows clipboard is a shared resource and can be locked by an application at any moment.
Should address https://github.com/dictation-toolbox/Caster/issues/657 OpenClipboard: Access denied
On failure the clipboard limited loops read write until success.
These changes could be integrated directly into dragonfly. Eliminating the need for these modifications.
https://github.com/dictation-toolbox/dragonfly/blob/7018e5c1c5c4249e8ec1ae47d12505f2bfd02764/dragonfly/actions/action_paste.py#L103
https://github.com/dictation-toolbox/dragonfly/blob/master/dragonfly/windows/clipboard.py
Needs to be tested with a broader audience given the rarity of the bug.
> Added Clipboard read\write retry attempts on failure

- castervoice/apps/griddouglas.py
- castervoice/apps/gridlegion.py
- castervoice/apps/gridrainbow.py
- castervoice/lib/ccr/standard.py
In each of `griddouglas.py`, `gridrainbow.py`, and `gridlegion.py` I replace the cancel phrase/spec with `SymbolSpecs.CANCEL`. I also added the options `exit | cancel` to `SymbolSpeaks.CANCEL` so that this is not a breaking change.
None.
The cancel phrase should be the same throughout for each user and they should only have to change the phrase in one place. 
No testing as yet as this is a simple change.
> # Switch mouse commands to use standard cancel phrase

- _caster.py
- castervoice/lib/ctrl/dependencies.py
- castervoice/lib/ctrl/nexus.py
- castervoice/lib/navigation.py
- setup.py
This request removes settings as a hard dependency for Dependency.py
https://github.com/dictation-toolbox/Caster/pull/676
This make sure that Caster checks dependencies before third party packages are called. This allows Dependency.py to check for missing or version specific dependencies.
This has been tested 
- Online and off-line Caster mode
- Removal of toml dependency 
- Past existing unit tests
- Created a [test package`](https://test.pypi.org/project/castervoice/) parsing of readme
- Mouse grids have been tested
> Remove settings as a hard dependency for Dependency.py

- castervoice/lib/dfplus/merge/ccrmerger.py
- castervoice/lib/github_automation.py
- castervoice/lib/settings.py
- castervoice/lib/utilities.py
- requirements-dev.txt
- requirements.txt
- setup.py
Implements [tomlkit](https://github.com/sdispater/tomlkit) place of [uiri/toml](https://github.com/uiri/toml) dependency.
A lot of credit goes to @comodoro for testing and breathing some life into the old issue.
Contains temporary a patch in place of https://github.com/dictation-toolbox/dragonfly/pull/125.
Original Pull Request https://github.com/dictation-toolbox/Caster/pull/372
Fixes non-ASCII characters in clipboard 
https://github.com/dictation-toolbox/caster/issues/357 
Implements sorting keys
https://github.com/dictation-toolbox/caster/issues/323
[uiri/toml](https://github.com/uiri/toml) is not being maintained enough for the purposes of our project.
`
String dump with correct escaping #244` pull request by **comodoro** has been open for 111 days without comment from the author. …
> Implements tomlkit in place of toml dependency

- castervoice/lib/text_manipulation_functions.py
Trivial change:
Remove unneeded itertools import at the top of text_manipulation_functions.py
I used itertools previously in this file before I found out about Repetition objects. itertools has not been used in this file for months.
> remove unneeded itertools import (trivial)

- docs/readthedocs/Aenea.md
I added one step to the Aenea setup instructions to let people know that they will have to copy `aenea.json` to their Caster install directory. I also added the location of `settings.toml` to the next step.
> Clarify Aenea setup instructions

- docs/README.md
Edit: Looks like the badge updated with passing on its own, however the URL still could be updated.
False positive for failing ReadTheDocs CI due to out of date badge.
Fixed by updating the ReadTheDocs badge
> [Trivial change]  Docs CI are passing but ReadTheDocs badge fails

- _caster.py
- castervoice/lib/settings.py
90% of the credit for this goes to @lettersandnumbersgithub. All I did was make it conditional in settings and based on engine type. 
Upon error status window will come to the forefront. Configurable `settings.toml` under `miscellaneous` "status_window_forefront_on_error" with Bool. Default set to false.
Note: Errors during initial caster startup do not bring the window to the forefront.
none
Often when working status window is in the foreground behind other windows. Think of the following scenarios.
- If an error occurs the user may not be aware of it leading to confusion.
- The user may want to check for an Error but has to manually bring the status window to the forefront
For reference status window
It is been tested to ensure the "status_window_forefront_on_error" are functional. …
> Upon error in Status Window will come to the forefront.

- castervoice/rules/apps/editor/sublime.py
Fix missing repeats in the sublime edit up/down/next commands
Fix missing repeats in the sublime edit up/down/next commands and import Repeat from dragonfly
In the newest version of Caster , In the sublime Grammar , the commands that should enable creating multiple coursers in the lines above or below the current one were missing their repeat action which caused them to behave as if the extra parameter was always one:
As a consequence, only adjacent lines could be edited simultaneously.
Manual testing, After changes:
> Fix missing repeats in the sublime edit up/down/next commands

- castervoice/asynch/settingswindow.py
It works in that it doesn't outright crash, but it's still ugly/glitchy.
The crash was due to the way settings initialization changed a few months ago. Once the settings were properly initialized, I was able to start the script normally.
Once I was successfully able to launch the settings window I discovered that all of the input elements for numbers were missing. This was due to an additional bug in the settings parsing code which was introduced with the switch `tomlkit`. The numbers were being passed over during window startup because `tomlkit` uses its own classes to represent real numbers. I changed the instance check to test against the built-in `numbers.Real` instead of `int`. This change is kind of minimal and hacky, but the proper changes would be quite extensive.
Ultimately, this …
> Pr settings window bandaid

- _caster.py
- castervoice/lib/ctrl/dependencies.py
- castervoice/lib/ctrl/updatecheck.py
- castervoice/rules/core/utility_rules/caster_rule.py
Re-factored `update_check` out of `DependencyMan`.
The motivation comes from two issues.
1. `update_check` relies on checking settings.toml for update. Previously this was checked before settings was initialized in _caster.py quantitatively initializing settings twice. Now settings is initialized in `_caster.py` before `update_check` is called.
2. `DependencyMan` dependencies are only standard library and runs before settings are initialized. This means if there's any missing/version specific dependencies the user will be notified appropriately instead of a trace back immediately.
- Ongoing `"python", "-m"` causes erroneous update notification in `["python", "-m", find_pip(), "search", command]` further testing is required.
The tricky bit `python -m  pip search dragonfly2` and `pip search …
> Initialized update_check after settings

- .gitignore
- castervoice/lib/navigation.py
- tests/test_util/utilities_mocking.py
- tests/testrunner.py
Fixed a bug where the multi-clipboard was being erased whenever it was **pasted from** before being **copied into**. This was due to failing to initialize the multi-clipboard on module load.
Initialization was segregated into a function during a refactor but that function was never called.
> Bug fix: multi-clipboard wasn't initialized.

- castervoice/rules/ccr/recording_rules/alias/base_alias.py
When the alias command is triggered by voice without a spec GUI appears for the user to input one. Previously this appeared whether or not the user had defined a spec. The GUI appears only in the correct conditions. 
none
See description
This is been tested both with the chain alias is and alias commands. Selecting text and saying the `alias` with `any word` and the GUI does not appear. Say `alias` without a word and GUI appears appropriately.
> Only trigger alias GUI without a defined alias spec

- castervoice/rules/ccr/recording_rules/again.py
`again do` always returned `if utterance[0] == "again": return` because the last entry going to be the `again` `do` command. Changing `last_utterance_index = 1` to `last_utterance_index = 2` ensures that it does not return so the function completes.
The Again grammar does not function as expected. #729
Tested with and without an integer.
> `again do`command set index 2 for last utterance

- tests/rules/ccr/test_rule_modules.py
- tests/rules/core/test_rule_modules.py
Separate core grammars into its own unit test that reflects caster file structure.
added hardware_rule, mouse_alts_rules, caster_rule, window_mgmt_rule
None
Best practice is to have your unit tests mimic the file structure of the project.
Run unit tests through pycharm 
95 to 99 unit tests and passing
if not applicable).
> Separate core grammars into unit test

- castervoice/lib/textformat.py
- castervoice/rules/core/navigation_rules/nav.py
- tests/lib/test_textFormat.py
When I am writing natural language,
for example in comments and READMEs,
I often wish the dictation would allow Dragon to
choose the capitalization method for me.
Sometimes I want to choose the initial letter, however.
As an example consider the phrase,
"My name is Dusty and I like to dictate"
If I dictate this without a caster command,
it comes up the way I want it to,
but I often use either 'Sing' or 'laws'
because I want to control the capitalization of the 1st letter,
or because I want to insert it with other commands in CCR mode.
When I do that to my example sentence,
it lowercases my name and the 1st person 'I.'
The 3 text formatting commands I've added
operate on only the 1st character, but leave the remaining
words is capitalized by Dragon.
> Pass-through text formatting commands

- castervoice/lib/ctrl/mgr/grammar_manager.py
Description
Simplifies error messages from the grammar manager specifically the function `def receive` is part of reloading grammars.
Previous error message
```
An error occurred while importing '<module 'Firefox' from 'C:\Users\Admin\AppData\Local\caster\rules\Firefox.py'>': Traceback (most recent call last):
File "C:\Users\Admin\Documents\Caster\castervoice\lib\ctrl\mgr\loading\load\content_loader.py", line 133, in _reimport_module
return reload_fn(module)
File "C:\Users\Admin\AppData\Local\caster\rules\Firefox.py", line 112, in <module>
hello
NameError: name 'hello' is not defined
2020-02-04 12:41:54,207 : ERROR : call
Exception during timer callback: 'NoneType' object is not iterable
Traceback (most recent call last):
File "C:\Python27\lib\site-packages\dragonfly2-0.20.0-py2.7.egg\drag …
```
> Simplify grammar manager error messages.

- castervoice/lib/ctrl/mgr/rule_details.py
Adds the try except block to _calculate_filepath_from_frame and deletes the stale .pyc file. More details and related tissue.
Technically this pull request does not fix the issue of caster trying to load stale `.pyc` A more advanced approach would be to delete the erroneous .pyc and rerun the function.
**Update** Implemented to Deleting stale .pyc. rerunning the function is prohibitive because `inspect.stack` does not contain the correct reference to the correct existing Python grammar file. To my knowledge this can only be resolved by restarting Caster.
Stale `.pyc` files can cause Caster to crash. #744
The message is printed in the exception rather than raised because Caster can continue running. The related rule related to the stale .pyc won't load until caster is reloaded.
Reference …
> Error handling for stale .pyc files

- _caster.py
- castervoice/lib/ctrl/mgr/grammar_manager.py
- castervoice/lib/merge/ccrmerging2/hooks/events/event_types.py
- castervoice/lib/merge/ccrmerging2/hooks/events/on_error_event.py
- castervoice/lib/merge/ccrmerging2/hooks/standard_hooks/show_window_on_error_hook.py
- castervoice/lib/settings.py
Re-implemented on error show window using hooks.
None
The previous implementation was not elegant using logging. A `OnError` event has been created with `ShowStatusWindowOnErrorHook`. Currently the event does not pass data to the hook. The Hook system has two distinct advantages over the previous logging implementation. 
1. ShowStatusWindowOnErrorHook can placed in the CodeBase selectively so that certain errors because that's desired behavior.
2. Does not require an error type to be triggered.
3. The feature can be enabled and disabled while Caster is running.
Show status window on error only occurs when there is an error reloading the grammar. Other hooks could be placed in the CodeBase as needed.
Tested reloading a grammar with an syntax error.
> Re-implemented on error show window using hooks

- castervoice/asynch/hmc/homunculus.py
- castervoice/asynch/mouse/grids.py
- castervoice/asynch/settingswindow_qt.py
- castervoice/asynch/settingswindow_wx.py
- castervoice/asynch/sikuli/server/xmlrpc_server.sikuli/xmlrpc_server.py
Fix issue #761 
The crash happens because logging enabled by default for the RPC
server interferes with the client-server communication when the server
runs on pythonw.
In addition, make sure that methods on GUI widgets are invoked on the
main thread.  When RPC server receives a command that manipulates GUI
widgets, it issues an event which handled on the main thread, and then
widget methods are called by the event handler on the main thread.
#761
Fixes a crash
Tested on Windows and macOS by running the GUI and interacting with it from Caster via dragonfly test engine
> Fix settings window crash on complete command on Windows

- castervoice/lib/ctrl/mgr/rule_details.py
- castervoice/lib/ctrl/mgr/rule_maker/mapping_rule_maker.py
- castervoice/lib/ctrl/mgr/validation/details/function_context_validator.py
- castervoice/lib/merge/ccrmerging2/ccrmerger2.py
This ad support for Dragonfly function context. Context class that evaluates a given function, whose return value is interpreted as a bool, determining whether the context is active.  
https://github.com/dictation-toolbox/Caster/issues/747
While AppContext does most of what we want FuncContext has significant use cases such as Enabling grammars by modes modes such as Vim and so forth.
This has been tested with mapping rules and app CCR. I have not managed to get of working with Global CCR. Rule detail validator's check FuncContext's function for a bool value and Global CCR type.
> Add Dragonfly FuncContext support

- docs/readthedocs/Rule_Construction/Dragonfly_Rules/Sample_File.md
- sample.py
The output of `"i choose <choice>" : Text("<choice>")` was just `<choice>`
> [Trivial change] Fix broken sample.py command

- castervoice/rules/core/navigation_rules/nav.py
- castervoice/rules/core/navigation_rules/nav2.py
I replaced the 3 existing F-key mapping rules with one rule for all 12.
The old ones had alternative triggers with word numbers which I didn't add. I don't know if other users or speech recognition solutions struggle to differentiate between numerals and number words, but Dragon doesn't need them and it adds complexity. Let me know if you think it's worth implementing it and I'll do it.
I also added 'F<n>' alongside the 'function<n>' merge rule so it's all the same across the board.
F-key implementation was inconsistent and the `function<n>` trigger is both cumbersome and might clash with other commands using the word "function".
Manually testing a bunch of different commands using F-keys.
> Standardising function keys

- docs/README.md
A link to the alias page in the docs pointed to Aenea instead.
> Trivial Change: fix alias link

- castervoice/rules/apps/editor/vscode_rules/vscode2.py
I think perhaps nobody used this command before... :-)
> Trivial change: Fix vscode previous pane goes left

- castervoice/lib/utilities.py
This pull request changes the command used to reboot caster when using the Kaldi engine. It did not work for me before making this alteration.
Trying "reboot caster" both before and after making this change.
> Alter reboot command Kaldi

- castervoice/rules/core/utility_rules/caster_rule.py
For my dragon, anyway, ccr is picked up as a single word.
> Fix `enable ccr` for dragon vocabulary

- castervoice/rules/ccr/rust_rules/rust.py
`enum` , `async`, and `await` are often misrecognized by dragon,
so having extra commands for them reduces frustrationand can.
The clone command is just a quick shortcut.
> Trivial change: Four new Rust syntax commands

- castervoice/lib/navigation.py
- castervoice/rules/core/navigation_rules/nav.py
I'm not sure if this is generally useful, so feel free to close.
This command adds a character at the end of the current line
and then insert a new line above.
It is symmetric to the `tell` command, which does the same thing,
except
goes below the current line.
both commands are analogous to the o and O commands in vim.
I chose `hark` as it is kind of the inverse of `tell`,
but dragon often hears it as `heart`, so I used both.
> Add command to open line above

- castervoice/lib/ctrl/mgr/loading/load/content_request_generator.py
This one fixes a bug I was seeing when using python 3 with a user file containing special characters.
> content_request_generator handles special characters UTF-8 py3

- castervoice/rules/apps/editor/vscode_rules/vscode.py
- docs/readthedocs/Caster_Commands/Application_Commands_Quick_Reference.md
1. Use the explicit indent and unindent VSCode commands
instead of simulating with home + tab.
The built-in commands work correctly with multiple cursors.
2. VSCode command to "skip next" the current cursor
This behaves like "next cursor" except that it removes the
current word from the selection.
This allows you to use next cursor interactively
such that you don't have to select all the words in a row.
> Two minor tweaks for vscode grammar (should be trivial)

- castervoice/rules/core/navigation_rules/nav2.py
- docs/readthedocs/Caster_Commands/Mouse.md
Initiate scrolling as an asynchronous action until the user says `cancel`.
command is `zinc sauce|dunce <speed>` where speed is one of super slowly, slowly, normal, fast and superfast.
I got tired of saying "scree dunce" repeatedly when I didn't know how far I wanted to scroll.
The existing `<direction> <time_in_seconds>` command does a similar thing, except that it moves the cursor while doing so.
The VSCode "scroll up/down" and "scroll page down/up" commands do a similar thing in that they don't move the cursor, but they do not operate continuously.
I chose the name zinc because it seems unique and Dragon is good at picking up the `z` sound.
I have tested the new command in VS code and chrome. In both cases it initiated scrolling in the correct direction and cancelled appropriately. I …
> New command to scroll mouse wheel continuously

- castervoice/lib/ctrl/mgr/rule_maker/mapping_rule_maker.py
- castervoice/lib/merge/ccrmerging2/ccrmerger2.py
Fix FuncContext 
Changes how Caster creates contexts for CCR/Mapping for applications context. Note not global context.
Background explanation with the bug #798
An amazing community! A big thank you goes to @mpourmpoulis with that right up and insights with this issue.
This PR fixes FuncContext functions from being evaluated twice, outside of context, and context ignoring the exe/ttitle.
This is been tested with app mapping and mergerules(CCR)
- Out of context - FuncContext is not evaluated and fails when set to False or True
- In context - FuncContext is evaluated once and Fails when set to False
- In context - FuncContext is evaluated once and Succeeds when set to True
Test Rule
```
from dragonfly import Function, Repeat, Choice, Dictation, MappingRule, Pause
from …
```
> Fix dragonfly `FuncContext` Caster App integration

- _caster.py
- castervoice/lib/ctrl/configure_engine.py
- castervoice/lib/ctrl/mgr/engine_manager.py
- castervoice/lib/ctrl/nexus.py
- castervoice/lib/settings.py
- docs/readthedocs/Caster_Settings/settings.md
- tests/lib/ctrl/test_EngineModesManager.py
Added setting change engine mic state and mode on caster startup defined in settings.toml 
Outside of changing modes on startup switching modes set_mic_mode and set_engine_mode will not be fully implemented until exclusivity is added for all engines.
```
"engine": {
"default_engine_mode": False, 
"engine_mode": "normal",
"default_mic": False, 
"mic_mode": "on"
},
```
Valid "mic_mode" settings.
```
'on': mic is on # default
'sleeping': mic from the sleeping and can be woken up by command
'off': mic off and cannot be turned back on by voice. (DNS Only)
```
Valid "engine_mode" settings.
```
'normal': dictation and command (Default: DNS only)
'dictation': Dictation only 
'command': Commands only (Default: Other engines)
'numbers': Numbers only
'spell': Spelling only
```
Relevant to …
> Added change engine mic state and mode on caster startup for DNS

- castervoice/lib/merge/ccrmerging2/ccrmerger2.py
- tests/lib/merge/ccrmerging2/test_CCRMerger2.py
- tests/testrunner.py
This is essentially part two of #820 that's tried to address #798 And took care of most of the work needed but left a couple of details open, like excluding function contexts from the computation of the negation context, In order to avoid an edge case that could leave the user without global commands. This problem is now taken care off without sometimes leaving two merged CCR's active
This is achieved by tweaking the matches function of context created to cache It's result So it can be reused precisely one more time! as a consequence, the context gets evaluated Only once even though it is used both for its own grammar as well as for negation context. Furthermore, the implementation does not depend on the order in which the contexts are being processed
> Restructure ccr context creation to fix problems with function contexts without ignoring them from the computation of the negation context

- castervoice/lib/ctrl/mgr/loading/load/content_loader.py
ok this is the solution We had discussed in our voice chat quite some time ago:)
During the discussion we had addressed a variety of issues that can arise with the current implementation If the user is not careful but the main issue these PR tries to address  is that it contained a race condition. 
In particular, the directory in which a grammar resides was only added to the path right before that grammar is loaded!
Now if another grammar loads before it  and it requests one of its support files (for instance say eclipse  Needs alphabet_support and it is loaded before alphabet)  and it uses a conditional import, depending on how It is written,  behavior  can be different than if it loaded after it because in the first case The directory containing the support file is not going to be in …
> Resolve race conditions during content loading when overriding support files

- castervoice/rules/ccr/recording_rules/alias/base_alias.py
- castervoice/rules/ccr/recording_rules/bringme.py
Some sort of basic sanity check was needed for Alias/BringMe. This PR implement stripping out all symbols except for alphabet and apostrophes from user created Alias/BringMe specs.
Basic sanity check for alias #694
Speech recognition engines don't expect special or numerical inspects. With the exception being of apostrophes. DNS does have some exceptions but this handles it for all engines supported by dragonfly.
Tested on DNS/WSR/Kaldi
> Sanitize BringMe/Alias specs

- castervoice/rules/ccr/recording_rules/again.py
The following PR fixes two bugs in the `Again` grammar.
1. Replaced Caster's `IntegerRefST` is an abstraction for Dragonfly `ShortIntegerRef`
For some reason Dragonfly `ShortIntegerRef` is much more accurate than casters abstraction via `IntegerRefST`
**Note**: This fixes the grammar. However if there is an issue with the underlying abstraction of `IntegerRefST` this needs to be evaluated in a new issue.
2. Fixed 'again do' speech recognition history conversion for dragonfly playback.
The errors occur primarily because the during the conversion to a list of strings for playback it assumes one word per string. DNS recognition history for built-in commands and proper pronouns can have multiple words/symbols as one string. The assumption in this new code is that the reported history by the …
> BugFix: `Again` grammar #833 and #834

- castervoice/rules/apps/editor/visualstudio.py
- docs/readthedocs/Caster_Commands/Application_Commands_Quick_Reference.md
- docs/readthedocs/Caster_Commands/CCR_languages_Quick_Reference.md
Add new shortcuts for Visual Studio
Visual Studio was lacking commands for a few basic features, specifically Go Back, Go Forward, Go to Definition, and Show References which I shortened to Show Refs. 
`resume` was an odd name for a command that begins a debug session, although it is the same keypress as a continue action when debug hits a breakpoint, so I also added an additional phrase `go to debug` to the f5 keypress.
These changes were tested in use against Visual Studio Professional 2019 and are voice commands for existing keyboard shortcuts. I believe these are all keyboard shortcuts that I used on previous versions of Visual Studio but no longer have them installed to verify.
I see in the checklist a reference to writing actual tests against the code, but I didn't see the tests and …
> Add new shortcuts for Visual Studio

- castervoice/rules/apps/editor/jetbrains.py
- docs/readthedocs/Caster_Commands/Application_Commands_Quick_Reference.md
Jetbrains Commands Updates
The documentation for the Jetbrains rules was clearly out of date with the code. I made code changes and then updated the documentation to match the code, so the documentation changes do look like I may have made more changes than I actually did. 
Of note, I renamed the commands:
"auto complete" to "find action". This shortcut previously coded opens a find dialog to find actions in the code. It does nothing even close to resembling auto complete.
"replace" to "replace [here]" - replace is currently getting overridden by the core replace and therefore broken. As referenced in gitter chat, this could also be resolved with a weighting workaround, but I figured adding an extra word of specificity would allow this to fallback to replace if kaldi does implement app …
> Jetbrains Commands Updates

- requirements-dev.txt
- requirements-mac-linux.txt
- requirements.txt
Found that this stopped caster working after a reinstall.
Current version is 1.15, do we want to specify version greater than that?
> add six to requirements (pretty trivial)

- castervoice/lib/contexts.py
Adds contexts for cross platform as per https://github.com/dictation-toolbox/dragonfly/issues/293
None.
Allows for platform contexts to be used in ContextAction.
In a ContextAction on another branch.
> Add contexts for cross platform

- castervoice/lib/ctrl/configure_engine.py
kaldi needs a default mic state "on" for sleep_timer
The sleep timer checks the current mic state every X seconds (Default 120). At the interval of the timer if the microphone is "on" the microphone will be put to sleep.
_Originally posted by @kendonB in https://github.com/dictation-toolbox/Caster/pull/856#issuecomment-709643781_
```
@LexiconCode on Kaldi there's a limitation in that the timer is not on until you load the sleeping grammar and that is only loaded once you first say "caster sleep" or "caster on". Is there a way we can turn this on right when caster starts?
```
Kaldi and DNS
> kaldi default mic state "on" for sleep_timer

- castervoice/asynch/mouse/legion.py
- castervoice/lib/gdi.py
- castervoice/rules/apps/mouse_grids/gridlegion.py
Most of the changes relate to clarifying encoding as is required Python 3.
The exception is in gdi.py `cleanup()`, where Python 3 won't let you make reference to an object which doesn't necessarily exist. In that bit, you have to refer to the potential object name as a string.
It also adds some weight to the legion clicker so that it works in Kaldi.
#838
Python 3 port.
On a Windows VirtualBox. Tested using both Python 3.8 and 2.7. Tested only using Kaldi. I just tried saying "legion" and "legion 2" and both worked.
> Fix Legion for Python 3

- castervoice/rules/core/keyboard_rules/keyboard.py
The keyboard grammar had used the punctuation keys from punctuation_support but not all of those characters (passed to `Text` in punctuation.py) exist in the dragonfly keyboard specification. This PR replaces those characters (" ", "-", "/", ",", and ":") with their respective dragonfly Key IDs ("space", "minus", "slash", "comma", and "colon").
The approach should be robust to people editing the specs in punctuation_support.
None. Mentioned on gitter
Fixing a bug
Just using the text engine
> add missing keyboard keys

- castervoice/rules/ccr/voice_dev_commands_rules/voice_dev_commands.py
- castervoice/rules/core/keyboard_rules/keyboard.py
- castervoice/rules/core/keyboard_rules/keyboard_support.py
- castervoice/rules/core/navigation_rules/nav.py
- tests/rules/core/test_rule_modules.py
- Refactors much of what was in the keyboard class into the keyboard_support.
- Cleans unused imports from keyboard.py
- Adds keyboard.py to unit tests
None
- It's unclear and difficult to manage when importing the keyboard class changes to choice objects. 
Choice objects that are imported by other grammars should be in support files.
The support files are imported only twice. Once to verify validity of Python on startup and once for all grammars regardless the number of imports of the keyboard support. ButtonDict in the support file now has a clear structure for ordering updates to the dictionary. Both modifier_choice_object and button_dictionary_1 have functions that scoped variables and execution order.
Testing a number of commands manually. It's too large to test all keyboard keys but …
> Re-factor keyboard dictionaries to keyboard_support

- docs/readthedocs/Caster_Commands/Keyboard.md
Update Keyboard.md to specify that hold and release can only be used on modifiers
> Clarify hold/release heys documentation

- requirements-dev.txt
- requirements.txt
The latest release of pyvda contains a major API rework which will break the usage in caster, and also remove support for Python 2.7.
I'm not sure what the status is of Caster re python 3 but for now I would suggest pinning to [0.0.8](https://pypi.org/project/pyvda/0.0.8/), which should work indefinitely.
> Pin pyvda to 0.0.8

- castervoice/rules/ccr/python_rules/python.py
> Correct typo python "reper" command

- castervoice/rules/core/navigation_rules/nav2.py
All in the title
None.
There are currently two ways to press the function keys - one in keyboard.py ("press f four") and one in nav2.py ("f four").
I think that we shouldn't have both and we should just keep the keyboard.py one. Neither are currently CCR. The F keys in nav2 do not appear to be documented anywhere.
A breaking change as users would now have to say "press f4" rather than just "f4".
Trivial enough
> Remove function keys from nav2

- castervoice/lib/navigation.py
Prevent multiple navigation overlays from stacking
Currently it's possible to trigger multiple navigation modes at once, causing grids like rainbow and sudoku to overlap with one another. This becomes confusing because it's not obvious what order is needed to exit these grids.
This change also check to see if any other navigation mode has been started, and if so, raises an exception so that the new navigation mode doesn't wait around for its window to appear.
I keep triggering multiple ones by accident and wanted to fix it.
Manual testing, tracking that new navigation modes can not be triggered if one is currently on the screen
> Prevent multiple navigation overlays from stacking

- Install_Caster_DNS-WSR.bat
- docs/readthedocs/Installation/Windows/Dragon_NaturallySpeaking.md
The Install_Caster_DNS-WSR.bat file uses a `py` alias to refer to `python`, even though setting that alias isn't an installation step. I've renamed the alias to the `python` executable, just like it's named in the Kaldi.bat
> Rename py to python in Install_Caster_DNS-WSR.bat

- docs/readthedocs/Installation/Windows/Dragon_NaturallySpeaking.md
This includes undocumented but required steps for installing natlink. This'll save me (and the next person) 30-60 minutes of effort the next time they install caster.
I also renamed the bullet points in the section to `1.`. This makes it easy to rearrange, add, and delete bullet points without needing to re-number them all, but it renders in the correct order.
> Included additional steps for installing natlink
